version: 0.1
log:
  fields:
    service: registry
storage:
  s3:
    accesskey: "MINIO_ACCESS_KEY"
    secretkey: "MINIO_SECRET_KEY"
    regionendpoint: "https://you-minio-storage.com"
    bucket: docker
    secure: "false"
    region: ignored-for-minio
  delete:
    enabled: "true"
  redirect:
    disable: "false"
http:
  addr: 0.0.0.0:443
  tls:
    certificate: /certs/wildcard-certificate.crt
    key: /certs/wildcard-certificate.key
auth:
  htpasswd:
    path: /auth/.htpasswd
    realm: "Registry Realm"
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3