version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:21.12.4.1-alpine
    container_name: clickhouse
    ports:
      - "58123:8123"
      - "59009:9000"
    volumes:
      - /media/psf/Docker/Clickhouse/log:/var/log/clickhouse-server
      - /media/psf/Docker/Clickhouse/conf/config.xml:/etc/clickhouse-server/config.xml
      - /media/psf/Docker/Clickhouse/data:/var/lib/clickhouse
    restart: on-failure
    networks:
      develop:
        ipv4_address: 172.19.0.40
    environment:
      CLICKHOUSE_UID: ${CLICKHOUSE_UID:-0}
      CLICKHOUSE_GID: ${CLICKHOUSE_GID:-0}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-default}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-root}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT:-1}
      TZ: "Asia/Shanghai"
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  develop:
    external: true