version: "3.9"

services:
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - published: 59100
        target: 9100
        protocol: tcp
        mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    configs:
      - source: prometheus_web_config
        target: /etc/prometheus/web.yml
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.config.file=/etc/prometheus/web.yml'
    deploy:
      mode: global
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    environment:
      TZ: "Asia/Shanghai"

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - published: 59101
        target: 8080
        protocol: tcp
        mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    configs:
      - source: cadvisor_htpasswd
        target: /auth/.htpasswd
    command:
      - '-logtostderr'
      - '-docker_only'
      - '-http_auth_file=/auth/.htpasswd'
    deploy:
      mode: global
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    environment:
      TZ: "Asia/Shanghai"

  ssl-exporter:
    image: ribbybibby/ssl-exporter:latest
    ports:
      - published: 59219
        target: 9219
        protocol: tcp
        mode: ingress
    command:
      - '--log.level=info'
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

configs:
  prometheus_web_config:
    name: prometheus_web_config_v1
    external: true
  cadvisor_htpasswd:
    name: cadvisor_htpasswd_v1
    file: ./conf/.htpasswd
