version: "3.9"

services:
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - published: 59100
        target: 9100
        protocol: tcp
        mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    configs:
      - source: prometheus_web_config
        target: /etc/prometheus/web.yml
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.config.file=/etc/prometheus/web.yml'
    deploy:
      mode: global
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

configs:
  prometheus_web_config:
    name: prometheus_web_config_v1
    external: true