version: "3.9"

services:
  filebeat:
    image: elastic/filebeat:7.11.1
    user: root
    labels:
      co.elastic.logs/enable: false
    networks:
      - cluster
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat:/usr/share/filebeat/data
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - KIBANA_HOST=${KIBANA_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    command: [ "--strict.perms=false" ]

configs:
  filebeat_config:
    name: filebeat_config_v1
    file: ./conf/filebeat.yml

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true

volumes:
  filebeat:
    name: filebeat
    external: false