version: "3.9"

services:
  filebeat:
    image: elastic/filebeat:7.11.1
    user: root
    labels:
      co.elastic.logs/enable: false
    networks:
      - elk
    volumes:
      - ./conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - filebeat:/usr/share/filebeat/data
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - KIBANA_HOST=${KIBANA_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    command: [ "--strict.perms=false" ]

networks:
  elk:
    name: elk
    external: true

volumes:
  filebeat:
    name: filebeat
    external: false