version: "3.9"

services:
  nfs-server:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: example/nfs-server:erichough
    container_name: nfs-server
    restart: "no"
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    environment:
      NFS_LOG_LEVEL: 'DEBUG'
    volumes:
      - ./data:/nfs/share
      - ./conf/intranet_exports.txt:/etc/exports:ro
      - /lib/modules:/lib/modules:ro