version: "3.9"

services:
  nfs:
    image: erichough/nfs-server
    container_name: nfs
    restart: "no"
    ports:
      - "52049:2049"
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      NFS_EXPORT_0: '/nfs-share  *(rw,sync,no_root_squash,no_all_squash,no_subtree_check,nohide,crossmnt)'
    command: tail -f /dev/null
    working_dir: /nfs-share
    volumes:
      - /your/path:/nfs-share
    networks:
      - develop

networks:
  develop:
    external: true

volumes:
  filebeat:
    name: filebeat
    external: true