version: "3.9"

services:
  registry:
    image: registry:${REGISTRY_VERSION:-2.7.1}
    ports:
      - "55050:443"
    networks:
      - cluster
    configs:
      - source: docker_registry_config
        target: /etc/docker/registry/config.yml
    secrets:
      - source: docker_registry_auth_htpasswd
        target: /auth/.htpasswd
      - wildcard-certificate.crt
      - wildcard-certificate.key
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true

configs:
  docker_registry_config:
    name: docker_registry_config_v2
    external: false
    file: ./conf/config.yml

secrets:
  docker_registry_auth_htpasswd:
    name: docker_registry_auth_htpasswd
    external: false
    file: ./conf/auth/.htpasswd
  wildcard-certificate.crt:
    name: wildcard-certificate.crt
    external: true
  wildcard-certificate.key:
    name: wildcard-certificate.key
    external: true