version: "3.9"

services:
  registry:
    image: registry:${REGISTRY_VERSION}
    container_name: registry
    restart: always
    ports:
      - "5050:443"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: ${REGISTRY_HTTP_TLS_CERTIFICATE}
      REGISTRY_HTTP_TLS_KEY: ${REGISTRY_HTTP_TLS_KEY}
      REGISTRY_AUTH: ${REGISTRY_AUTH}
      REGISTRY_AUTH_HTPASSWD_PATH: ${REGISTRY_AUTH_HTPASSWD_PATH}
      REGISTRY_AUTH_HTPASSWD_REALM: ${REGISTRY_AUTH_HTPASSWD_REALM}
    volumes:
      - docker-registry:/var/opt/gitlab/gitlab-rails/shared/registry
      - ./conf/config.yml:/etc/docker/registry/config.yml:rw
      - ../Nginx/conf/ssl/*.***REMOVED***.crt:${REGISTRY_HTTP_TLS_CERTIFICATE}:ro
      - ../Nginx/conf/ssl/*.***REMOVED***.key:${REGISTRY_HTTP_TLS_KEY}:ro
      - ./conf/auth:/auth
    networks:
      - registry

networks:
  registry:
    name: develop
    external: true

volumes:
  docker-registry:
    name: docker-registry
    external: false