version: "3.5"

services:

  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
      - registry:/etc/docker/registry/config.yml
    networks:
      - registry
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2
      placement:
        constraints:
          - 'node.hostname == Cloud'

networks:
  registry:
    name: registry
    driver: overlay

volumes:
  registry:
    driver: local
    name: registry