version: "3.9"

services:
  registry:
    image: registry:${REGISTRY_VERSION}
    container_name: registry
    restart: always
    ports:
      - "63816:443"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/wildcard-certificate.crt
      REGISTRY_HTTP_TLS_KEY: /certs/wildcard-certificate.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - docker-registry:/var/lib/registry:rw
      - ./conf/config.yml:/etc/docker/registry/config.yml:rw
      - ./conf/auth:/auth
      - ../Nginx/conf/ssl/*.***REMOVED***.crt:/certs/wildcard-certificate.crt:ro
      - ../Nginx/conf/ssl/*.***REMOVED***.key:/certs/wildcard-certificate.key:ro
    networks:
      - registry

networks:
  registry:
    name: develop
    external: true

volumes:
  docker-registry:
    name: docker-registry
    external: false