version: '3.8'

services:

  registry:
    image: registry
    container_name: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./data/registry:/var/lib/registry
      - ./data/config.yml:/etc/docker/registry/config.yml
    networks:
      - registry

networks:
  registry: