version: "3.9"

services:
  registry:
    image: registry:${REGISTRY_VERSION}
    container_name: registry
    hostname: ${HOST_NAME}
    restart: always
    extra_hosts:
      - minio.***REMOVED***:${MINIO_HOST}
    ports:
      - "63813:443"
    environment:
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_ACCESSKEY: ${MINIO_ACCESS_KEY}
      REGISTRY_STORAGE_S3_SECRETKEY: ${MINIO_SECRET_KEY}
      REGISTRY_STORAGE_S3_REGIONENDPOINT: ${MINIO_DOMAIN}
      REGISTRY_STORAGE_S3_BUCKET: ${MINIO_BUCKET}
      REGISTRY_STORAGE_S3_SECURE: "false"
      REGISTRY_STORAGE_S3_REGION: ignored-for-minio
      REGISTRY_STORAGE_S3_CHUNKSIZE: 51214400
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE_REDIRECT_DISABLE: "false"
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/wildcard-certificate.crt
      REGISTRY_HTTP_TLS_KEY: /certs/wildcard-certificate.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: basic-realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/.htpasswd
    working_dir: /var/lib
    volumes:
      - ./conf/config.yml:/etc/docker/registry/config.yml:rw
      - ./conf/auth:/auth
      - "../Nginx/conf/ssl/*.***REMOVED***.crt:/certs/wildcard-certificate.crt:ro"
      - "../Nginx/conf/ssl/*.***REMOVED***.key:/certs/wildcard-certificate.key:ro"
    networks:
      - registry

networks:
  registry:
    name: develop
    external: true

volumes:
  registries:
    name: registries
    external: false