version: "3.7"

services:

  registry:
    image: registry
    container_name: registry
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    volumes:
      - ./data/registry:/var/lib/registry
      - ./data/config.yml:/etc/docker/registry/config.yml
    networks:
      - registry

networks:
  registry: