version: "3.9"

services:
  registry:
    image: registry:${REGISTRY_VERSION:-2.7.1}
    ports:
      - published: 55050
        target: 443
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    configs:
      - source: localtime_shanghai
        target: /etc/localtime
      - source: docker_registry_config
        target: /etc/docker/registry/config.yml
    secrets:
      - source: docker_registry_auth_htpasswd
        target: /auth/.htpasswd
        mode: 0600
      - source: wildcard-certificate.crt
        mode: 0600
      - source: wildcard-certificate.key
        mode: 0600
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true

configs:
  localtime_shanghai:
    name: localtime_shanghai
    external: true
  docker_registry_config:
    name: docker_registry_config_v1
    file: ./conf/config.yml

secrets:
  docker_registry_auth_htpasswd:
    name: docker_registry_auth_htpasswd_v1
    file: ./conf/auth/.htpasswd
  wildcard-certificate.crt:
    name: wildcard_certificate_crt_v2
    external: true
  wildcard-certificate.key:
    name: wildcard_certificate_key_2
    external: true