version: "3.9"

services:
  downloader:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: centos:7
    container_name: downloader
    restart: "no"
    volumes:
      - ./conf/yum.repos.d:/etc/yum.repos.d:rw
      - ./conf/yum.conf:/etc/yum.conf:rw
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"
    command: tail -f /dev/null

  volume_backup:
    image: centos:7
    container_name: volume_backup
    restart: "no"
    volumes:
      - ./data:/backup
      - source_data:/volume
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"
    command: tail -f /dev/null
    # command: tar -cvzf /backup/backup.tar.gz  -C /volume .

  volume_restore:
    depends_on:
      - volume_backup
    image: centos:7
    container_name: volume_restore
    restart: "no"
    volumes:
      - ./data:/backup
      - target_data:/volume
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"
    command: tail -f /dev/null
    # command: sh -c "rm -rf /volume/* /volume/..?* /volume/.[!.]* ; tar -xvzf /backup/backup.tar.gz -C /volume"


volumes:
  source_data:
    name: portainer_data
  target_data:
    name: test_data

networks:
  develop:
    external: true