version: "3.9"

services:
  downloader:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: centos:7
    container_name: downloader
    restart: "no"
    volumes:
      - ./conf/yum.repos.d:/etc/yum.repos.d:rw
      - ./conf/yum.conf:/etc/yum.conf:rw
    networks:
      - develop
    command: echo 'please recreate container before download'

  volume_backup:
    image: centos:7
    container_name: volume_backup
    restart: "no"
    volumes:
      - ./data:/backup
      - source_data:/volume
    command: tar -cvzf /backup/backup.tar.gz  -C /volume .

  volume_restore:
    depends_on:
      - volume_backup
    image: centos:7
    container_name: volume_restore
    restart: "no"
    volumes:
      - ./data:/backup
      - target_data:/volume
    command: sh -c "rm -rf /volume/* /volume/..?* /volume/.[!.]* ; tar -xvzf /backup/backup.tar.gz -C /volume"


volumes:
  source_data:
    name: portainer_data
    external: true
  target_data:
    name: test_data
    external: true

networks:
  develop:
    external: true