version: "3.9"

services:
  volume_backup:
    image: centos:7
    networks:
      - cluster
    volumes:
      - nfs_data:/backup
      - source_data:/volume
    command: tail -f /dev/null
    # command: tar -cvzf /backup/backup.tar.gz  -C /volume .
    # command: sh -c "rm -rf /volume/* /volume/..?* /volume/.[!.]* ; tar -xvzf /backup/backup.tar.gz -C /volume"
    working_dir: /backup
    environment:
      TZ: "Asia/Shanghai"
    deploy:
      mode: global
      restart_policy:
        condition: none
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != ShangHai-CentOS
          - node.hostname != California-CentOS
          - node.platform.os == linux

volumes:
  nfs_data:
    name: nfs_data
    driver_opts:
      type: "nfs"
      o: "addr=nfs.example.online,nolock,soft,rw"
      device: ":/nfs/share"
  source_data:
    name: bark_data

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true