version: "3.9"

services:
  builder:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: centos:7-builder
    container_name: builder
    restart: "no"
    volumes:
      - "./conf/yum.repos.d:/etc/yum.repos.d:rw"
      - "./conf/yum.conf:/etc/yum.conf:rw"
      - "/data/cache/maven:/root/.m2"
      - "/data/cache/bower:/root/.cache/bower"
      - "/data/cache/npm:/root/.npm"
      - "/data/cache/composer:/root/.composer"
      - "/data/cache/gradle:/root/.gradle"
      - "/data/cache/golang:/var/lib/go/pkg"
    working_dir: /backup
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"
    command: tail -f /dev/null

  downloader:
    image: centos:7-builder
    container_name: downloader
    restart: "no"
    volumes:
      - ./data/download:/download
      - backup:/data
    working_dir: /backup
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"
    # back up data
    # command: tar -cvzf /data/rpms.tar.gz  -C /download .
    #
    # recovery data
    # command: sh -c "rm -rf /data/* /data/..?* /data/.[!.]* ; tar -xvzf /data/rpms.tar.gz -C /download"
    command: tail -f /dev/null

volumes:
  backup:
    name: bark_data

networks:
  develop:
    external: true