version: "3.9"

services:
  downloader:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: centos:7
    container_name: downloader
    restart: "no"
    volumes:
      - ./conf/yum.repos.d:/etc/yum.repos.d:rw
      - ./conf/yum.conf:/etc/yum.conf:rw
    working_dir: /backup
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"
    command: tail -f /dev/null

  volume_backup:
    image: centos:7
    container_name: volume_backup
    restart: "no"
    volumes:
      - ./data:/backup
      - source_data:/volume
    working_dir: /backup
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"
    # command: tar -cvzf /backup/backup.tar.gz  -C /volume .
    # command: sh -c "rm -rf /volume/* /volume/..?* /volume/.[!.]* ; tar -xvzf /backup/backup.tar.gz -C /volume"
    command: tail -f /dev/null

volumes:
  source_data:
    name: bark_data

networks:
  develop:
    external: true