version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data/:rw
    networks:
      - develop
    environment:
      POSTGRES_PASSWORD: example

networks:
  develop:
    external: true