version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "55432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data/:rw
    networks:
      - develop
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}

networks:
  develop:
    external: true