version: "3.9"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-13.5}
    container_name: postgres
    restart: "no"
    ports:
      - "55432:5432"
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf:rw
      - ./data:/var/lib/postgresql/data:rw
    networks:
      - develop
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"

networks:
  develop:
    external: true