version: "3.9"

services:
  swagger-edit:
    image: swaggerapi/swagger-editor:${SWAGGER_EDIT_VERSION:-v3.18.2}
    container_name: "swagger-edit"
    restart: always
    ports:
      - "58081:8080"
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"

  swagger-ui:
    image: swaggerapi/swagger-ui:${SWAGGER_UI_VERSION:-v3.52.5}
    container_name: "swagger-ui"
    restart: always
    ports:
      - "58082:8080"
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"

networks:
  develop:
    external: true