version: "3.9"

services:
  swagger-edit:
    image: swaggerapi/swagger-editor:${SWAGGER_VERSION:-v3.18.2}
    ports:
      - published: 58081
        target: 8080
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

  swagger-ui:
    image: swaggerapi/swagger-ui:${SWAGGER_VERSION:-v3.52.5}
    ports:
      - published: 58082
        target: 8080
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true