version: "3.9"

services:
  swagger-edit:
    image: swaggerapi/swagger-editor:${SWAGGER_VERSION:-latest}
    ports:
      - "63823:8080"
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != Bandwagon
          - node.platform.os == linux

  swagger-ui:
    image: swaggerapi/swagger-ui:${SWAGGER_VERSION:-latest}
    ports:
      - "63824:8080"
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != Bandwagon
          - node.platform.os == linux

networks:
  cluster:
    name: cluster
    driver: overlay
    external: true