version: "3.9"

services:
  swagger-edit:
    image: swaggerapi/swagger-editor:v4.10.0
    ports:
      - published: 58081
        target: 8080
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    configs:
      - source: swagger_definition
        target: /usr/share/nginx/html/data/real-world.yml
    environment:
      TZ: "Asia/Shanghai"
      URL: "./data/real-world.yml"

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.19.0
    ports:
      - published: 58082
        target: 8080
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    configs:
      - source: swagger_config
        target: /usr/share/nginx/html/swagger-config.json
      - source: swagger_definition
        target: /usr/share/nginx/html/data/real-world.yml
    environment:
      TZ: "Asia/Shanghai"
      CONFIG_URL: "./swagger-config.json"

configs:
  swagger_config:
    name: swagger_config_v1
    file: ./conf/swagger-config.json
  swagger_definition:
    name: swagger_definition_v1
    file: ./data/real-world.yml

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true