version: "3.9"

services:
  swagger-edit:
    image: swaggerapi/swagger-editor:${SWAGGER_VERSION:-latest}
    ports:
      - "58081:8080"
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux

  swagger-ui:
    image: swaggerapi/swagger-ui:${SWAGGER_VERSION:-latest}
    ports:
      - "58082:8080"
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true