version: "3.9"

services:
  swagger-edit:
    image: swaggerapi/swagger-editor:${SWAGGER_EDIT_VERSION:-v4.4.1}
    container_name: "swagger-edit"
    restart: always
    ports:
      - "58081:8080"
    networks:
      - develop
    volumes:
      - ./data:/usr/share/nginx/html/data:rw
    environment:
      TZ: "Asia/Shanghai"
      URL: ${URL}

  swagger-ui:
    image: swaggerapi/swagger-ui:${SWAGGER_UI_VERSION:-v4.14.1}
    container_name: "swagger-ui"
    restart: always
    ports:
      - "58082:8080"
    networks:
      - develop
    volumes:
      - ./conf/swagger-config.json:/usr/share/nginx/html/swagger-config.json:rw
      - ./data:/usr/share/nginx/html/data:rw
    environment:
      TZ: "Asia/Shanghai"
      CONFIG_URL: ${CONFIG_URL}


networks:
  develop:
    external: true