version: "3.8"

services:
  edit:
    image: swaggerapi/swagger-editor
    container_name: "swagger-edit"
    restart: always
    ports:
      - 8081:8080
    networks:
      - develop
  ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    restart: always
    ports:
      - 8082:8080
    networks:
      - develop

networks:
  develop:
    external: true