version: "3.9"

services:
  swagger-edit:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
    networks:
      - cluster
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - 'node.labels.cloud == true'

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    networks:
      - cluster
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - 'node.labels.cloud == true'

networks:
  cluster:
    name: cluster
    driver: overlay