version: "3.9"

services:
  qinglong:
    image: whyour/qinglong:2.11
    ports:
      - published: 55700
        target: 5700
        protocol: tcp
        mode: ingress
    volumes:
      - qinglong_data:/ql
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.hostname == GuangZhou-Ubuntu
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

volumes:
  qinglong_data:
    name: qinglong_data

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true