version: "3.9"

services:
  qinglong:
    image: whyour/qinglong:latest
    ports:
      - "0.0.0.0:55700:5700"
    volumes:
      - qinglong_data:/ql
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux

volumes:
  qinglong_data:
    name: qinglong_data

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true