version: "3.9"

services:
  qinglong:
    image: whyour/qinglong:${QINGLONG_VERSION:-2.11}
    container_name: qinglong
    restart: unless-stopped
    ports:
      - "0.0.0.0:55700:5700"
    networks:
      develop:
        ipv4_address: 172.19.0.37
    volumes:
      - /media/psf/Docker/Qinglong/log:/ql/log
      - /media/psf/Docker/Qinglong/conf:/ql/config
      - /media/psf/Docker/Qinglong/data/db:/ql/db
      - /media/psf/Docker/Qinglong/data/scripts:/ql/scripts
      - /media/psf/Docker/Qinglong/data/repo:/ql/repo
      - /media/psf/Docker/Qinglong/data/raw:/ql/raw
    environment:
      TZ: "Asia/Shanghai"

networks:
  develop:
    external: true