## Filebeat configuration
## https://github.com/elastic/beats/blob/master/deploy/docker/filebeat.docker.yml
#

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    # The Docker autodiscover provider automatically retrieves logs from Docker
    # containers as they start and stop.
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  # Docker compose
  # hosts: ['http://elasticsearch:9200']

  # Docker swarm
  # To scale Elasticsearch in Swarm mode, configure seed hosts with the DNS name tasks.elasticsearch instead of elasticsearch.
  hosts: ["http://tasks.elasticsearch:9200"]
  username: elastic
  password: ${ELASTIC_PASSWORD}

setup.kibana:
  # Docker compose
  # hosts: ['http://elasticsearch:9200']

  # Docker swarm
  # To scale Elasticsearch in Swarm mode, configure seed hosts with the DNS name tasks.elasticsearch instead of elasticsearch.
  hosts: ["http://tasks.kibana:5601"]
  username: elastic
  password: ${ELASTIC_PASSWORD}

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/7.17/http-endpoint.html
#

http.enabled: true
http.host: 0.0.0.0