version: "3.9"

services:
  filebeat:
    build:
      context: ./build/filebeat
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: filebeat
    #depends_on:
    #  - elasticsearch
    restart: "no"
    # Run as 'root' instead of 'filebeat' (uid 1000) to allow reading
    # 'docker.sock' and the host's filesystem.
    user: root
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/filebeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/7.17/config-file-permissions.html
      - --strict.perms=false
    volumes:
      - /media/psf/Docker/Nginx/log:/var/log/nginx:ro
      - /media/psf/Docker/Beats/conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /media/psf/Docker/Beats/conf/filebeat/modules.d:/usr/share/filebeat/modules.d:ro
      - /media/psf/Docker/Beats/conf/localtime:/etc/localtime
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD-changeme}
    networks:
      - develop

networks:
  develop:
    name: develop
    driver: bridge
    external: true