version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.37.8
    container_name: prometheus
    ports:
      - "59090:9090"
    volumes:
      - /media/psf/Docker/Prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - /media/psf/Docker/Prometheus/conf/web.yml:/etc/prometheus/web.yml
      - /media/psf/Docker/Prometheus/data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.config.file=/etc/prometheus/web.yml
      - --storage.tsdb.retention.time=15d
    restart: on-failure
    user: root
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"

networks:
  develop:
    external: true