version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.37.8
    ports:
      - published: 59090
        target: 9090
        protocol: tcp
        mode: ingress
    user: 0:0
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus_node_rule_config
        target: /etc/prometheus/rules/node.yml
      - source: prometheus_web_config
        target: /etc/prometheus/web.yml
    volumes:
      - prometheus_data:/prometheus:rw
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.config.file=/etc/prometheus/web.yml
      - --storage.tsdb.retention.time=15d
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
    environment:
      TZ: "Asia/Shanghai"

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - published: 59091
        target: 9091
        protocol: tcp
        mode: ingress
    user: 0:0
    volumes:
      - pushgateway_data:/var/lib/pushgateway:rw
    configs:
      - source: prometheus_web_config
        target: /etc/prometheus/web.yml
    command:
      - --persistence.file="/var/lib/pushgateway"
      - --persistence.interval=5m
      - --web.config.file=/etc/prometheus/web.yml
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
    environment:
      TZ: "Asia/Shanghai"

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - published: 59093
        target: 9093
        protocol: tcp
        mode: ingress
    user: 0:0
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/alertmanager.yml
      - source: prometheus_web_config
        target: /etc/prometheus/web.yml
    volumes:
      - alertmanager_data:/var/lib/alertmanager:rw
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --web.config.file=/etc/prometheus/web.yml
      - --storage.path=/var/lib/alertmanager
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
    environment:
      TZ: "Asia/Shanghai"

configs:
  prometheus_config:
    name: prometheus_config_v1
    file: conf/prometheus/prometheus.yml
  prometheus_node_rule_config:
    name: prometheus_node_rule_config_v1
    file: conf/prometheus/rules/node.yml
  prometheus_web_config:
    name: prometheus_web_config_v1
    file: conf/web.yml
  alertmanager_config:
    name: alertmanager_config_v1
    file: conf/alertmanager/alertmanager.yml

volumes:
  prometheus_data:
    driver: local
    name: prometheus
  alertmanager_data:
    driver: local
    name: alertmanager
  pushgateway_data:
    driver: local
    name: pushgateway

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true