version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.37.8
    ports:
      - published: 59090
        target: 9090
        protocol: tcp
        mode: ingress
    user: 0:0
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus_auth_config
        target: /etc/prometheus/web.yml
    volumes:
      - prometheus_data:/prometheus:rw
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.config.file=/etc/prometheus/web.yml
      - --storage.tsdb.retention.time=15d
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
    environment:
      TZ: "Asia/Shanghai"

configs:
  prometheus_config:
    name: prometheus_config_v1
    file: ./conf/prometheus.yml
  prometheus_auth_config:
    name: prometheus_auth_config_v1
    file: ./conf/web.yml

volumes:
  prometheus_data:
    driver: local
    name: prometheus

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true