version: "3.9"

services:
  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - published: 53000
        target: 3000
        protocol: tcp
        mode: ingress
    user: 0:0
    configs:
      - source: grafana_config
        target: /etc/grafana/grafana.ini
    volumes:
      - grafana_data:/var/lib/grafana:rw
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == California-CentOS
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      TZ: "Asia/Shanghai"

configs:
  grafana_config:
    name: grafana_config_v1
    file: ./conf/grafana.ini

volumes:
  grafana_data:
    driver: local
    name: grafana

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true