version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:${RABBIT_MQ_VERSION:-3.8.19-management}
    ports:
      - published: 15672
        target: 15672
        protocol: tcp
        mode: ingress
      - published: 55672
        target: 5672
        protocol: tcp
        mode: ingress
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:rw
    configs:
      - source: localtime_shanghai
        target: /etc/localtime
      - source: rabbitmq_config
        target: /etc/rabbitmq/conf.d/rabbitmq.conf
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

configs:
  localtime_shanghai:
    name: localtime_shanghai
    external: true
  rabbitmq_config:
    name: rabbitmq_config_v1
    file: ./conf/rabbitmq.conf

volumes:
  rabbitmq_data:
    name: rabbitmq_data
    driver: local
    external: false

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true
