version: '3'

services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: "gitlab"
    restart: always
    hostname: 'gitlab.banjintaohua.online'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url = 'https://gitlab.banjintaohua.online'
        gitlab_rails['gitlab_shell_ssh_port'] = 57891
        nginx['enable'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    ports:
      - '8181:80'
      - '8443:443'
      - '57891:22'
    volumes:
      - '/usr/local/opt/gitlab/config:/etc/gitlab'
      - '/usr/local/opt/gitlab/logs:/var/log/gitlab'
      - '/usr/local/opt/gitlab/data:/var/opt/gitlab'