version: "3.9"

services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_VERSION-13.12.15-ce.0}
    container_name: gitlab
    restart: always
    hostname: ${HOST_NAME}
    networks:
      - develop
    ports:
      - "50022:22"
      - "58080:80"
    environment:
      TZ: "Asia/Shanghai"
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${HOST_NAME}"
        gitlab_rails['gitlab_shell_ssh_port'] = 50022
    working_dir: /var/lib
    volumes:
      - /media/psf/Docker/Gitlab/log:/var/log/gitlab:rw
      - /media/psf/Docker/Gitlab/conf/gitlab:/etc/gitlab:rw
      - /media/psf/Docker/Gitlab/data:/var/opt/gitlab:rw

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    networks:
      - develop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mac: /Users/Shared/gitlab-runner/config
      # Linux: /srv/gitlab-runner/config
      - /srv/gitlab-runner/config:/etc/gitlab-runner:rw
      - /media/psf/Docker/Gitlab/conf/ssh/id_rsa:/home/gitlab-runner/.ssh/id_rsa:rw
      - /media/psf/Docker/Gitlab/conf/ssh/id_rsa.pub:/home/gitlab-runner/.ssh/id_rsa.pub:rw
    environment:
      TZ: "Asia/Shanghai"

networks:
  develop:
    name: develop
    external: true