version: "3.7"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.***REMOVED***
    ports:
      - 9022:22
      - 9080:80
      - 9443:443
    volumes:
      - ./conf:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
