version: '3'

services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: "gitlab"
    restart: always
    hostname: 'gitlab.banjintaohua.online'
    ports:
      - '8182:80'
      - '8443:443'
      - '57891:22'
    volumes:
      - './conf:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
