version: "3.9"

services:
  gitlab:
    image: gitlab/gitlab-ce:13.12.15-ce.0
    networks:
      - cluster
    ports:
      - published: 50022
        target: 22
        protocol: tcp
        mode: ingress
      - published: 58080
        target: 80
        protocol: tcp
        mode: ingress
    environment:
      TZ: "Asia/Shanghai"
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    working_dir: /var/lib
    configs:
      - source: gitlab_config
        target: /omnibus_config.rb
    secrets:
      - source: gitlab_root_password
        mode: 0600
    volumes:
      - gitlab_data:/var/opt/gitlab:rw
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 1
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == GuangZhou-CentOS
          - node.platform.os == linux

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == GuangZhou-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

configs:
  gitlab_config:
    name: gitlab_config_v1
    external: false
    file: ./conf/gitlab.rb

secrets:
  gitlab_root_password:
    name: gitlab_root_password_v1
    external: false
    file: ./conf/root_password.txt

volumes:
  gitlab_data:
    name: gitlab_data
    driver: local
    external: false

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true