version: "3.9"

services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - 8182:80
      - 8443:443
      - 57891:22
    volumes:
      - /usr/local/opt/gitlab/config:/etc/gitlab
      - /usr/local/opt/gitlab/logs:/var/log/gitlab
      - /usr/local/opt/gitlab/data:/var/opt/gitlab
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.hostname == Cloud"
          - "node.id == 9vkhpxkv570xojyy17alr7t76"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 1m30s

