version: "3.9"

services:
  mongodb:
    image: mongo:${MONGO_VERSION:-4.2.18}
    container_name: mongodb
    restart: always
    ports:
      - "57017:27017"
    volumes:
      - /media/psf/Docker/MongoDB/log:/var/log/mongodb:rw
      - /media/psf/Docker/MongoDB/conf/mongod.conf:/etc/mongod.conf:rw
      - /media/psf/Docker/MongoDB/data:/var/lib/mongodb:rw
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}

networks:
  develop:
    external: true