version: "3.9"

services:
  code-server:
    image: codercom/code-server:${CODE_SERVER_VERSION:-4.0.2}
    container_name: code-server
    restart: "no"
    user: 0:0
    ports:
      - "58083:8080"
    volumes:
      - /media/psf/Docker/VSCode/conf/.config:/home/coder/.config:rw
      - /media/psf/Docker/VSCode/data/project:/home/coder/project:rw
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"

networks:
  develop:
    name: develop
    external: true