version: "3.9"

services:
  vscode:
    image: codercom/code-server:${CODE_SERVER_VERSION:-3.9.1}
    ports:
      - "63827:8080"
    user: 0:0
    volumes:
      - vscode:/home/coder/project:rw
      - vscode:/home/coder/.local/share/code-server:rw
    networks:
      - cluster
    environment:
      PASSWORD: ${PASSWORD:-***REMOVED***}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == GuangZhou-CentOS

volumes:
  vscode:
    driver: local
    name: vscode

networks:
  cluster:
    name: cluster
    external: true