version: "3"

services:
  code_server:
    image: codercom/code-server
    command: --allow-http --password "task@3389"
    ports:
      - "60025:8443"
    volumes:
      - "/home/docker/codeserver/project:/home/coder/project"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.code_server==true