version: "3.9"

services:
  code-server:
    container_name: code-server
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        CODE_SERVER_VERSION: $CODE_SERVER_VERSION
    restart: always
    user: 0:0
    ports:
      - "8080:8080"
    volumes:
      - ./data/project:/home/coder/project
    environment:
      PASSWORD: ${PASSWORD}