version: "3.5"

services:
  code-server:
    image: codercom/code-server:v2
    ports:
      - 8080:8080
    volumes:
      - vscode:/home/coder/project
      - vscode:/home/coder/.local/share/code-server
    environment:
      - PASSWORD=password
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2
      placement:
        constraints:
          - 'node.hostname == Cloud'
          - 'node.id == 0s4487ohhl7elxnugia34tbwl'
          - 'node.labels.vscode == true'

volumes:
  vscode:
    driver: local
    name: vscode