version: "3.9"

services:
  code-server:
    image: codercom/code-server:${CODE_SERVER_VERSION:-4.0.2}
    restart: "no"
    user: 0:0
    ports:
      - "58083:8080"
    volumes:
      - ./conf/.config:/home/coder/.config:rw
      - ./data/project:/home/coder/project:rw