version: "3.9"

services:
  vscode:
    image: codercom/code-server:${CODE_SERVER_VERSION:-4.0.2}
    ports:
      - published: 58083
        target: 8080
        protocol: tcp
        mode: ingress
    user: 0:0
    configs:
      - source: vscode_config
        target: /root/.config/code-server/config.yaml
    volumes:
      - vscode_data:/home/coder/project:rw
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == GuangZhou-CentOS
          - node.hostname != California-CentOS
    environment:
      TZ: "Asia/Shanghai"

configs:
  vscode_config:
    name: vscode_config_v1
    file: ./conf/.config/code-server/config.yaml

volumes:
  vscode_data:
    driver: local
    name: vscode

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true