version: "3.9"

services:
  code-server:
    image: codercom/code-server:${CODE_SERVER_VERSION:-3.9.1}
    ports:
      - "8083:8080"
    volumes:
      - vscode:/home/coder/project
      - vscode:/home/coder/.local/share/code-server
    networks:
      - cluster
    environment:
      PASSWORD: ${PASSWORD:-password}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.oversea != true

volumes:
  vscode:
    driver: local
    name: vscode

networks:
  cluster:
    name: cluster
    external: true