version: "3.9"

services:
  vscode:
    image: codercom/code-server:${CODE_SERVER_VERSION:-4.0.2}
    ports:
      - "58083:8080"
    user: 0:0
    configs:
      - source: vscode-config
        target: /root/.config/code-server/config.yaml
    volumes:
      - vscode:/home/coder/project:rw
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == GuangZhou-CentOS
          - node.hostname != California-CentOS

configs:
  vscode-config:
    name: vscode-config
    file: ./conf/.config/code-server/config.yaml

volumes:
  vscode:
    driver: local
    name: vscode

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true