version: "3.9"

services:
  code-server:
    container_name: code-server
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        CODE_SERVER_VERSION: ${CODE_SERVER_VERSION:-3.9.1}
    restart: always
    user: 0:0
    ports:
      - "40012:8080"
    environment:
      PASSWORD: ${PASSWORD:ch@ngeme}
    volumes:
      - ./data/project:/home/coder/project:rw