version: "3.7"

services:
  code-server:
    container_name: code-server
    image: codercom/code-server:v2
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: 0:0
    ports:
      - "8080:8080"
    volumes:
      - /usr/local/opt/vscode/project:/home/coder/project
      - /usr/local/opt/vscode/.local/share/code-server:/home/coder/.local/share/code-server
    environment:
      - PASSWORD=${PASSWORD:-password}