version: '3.8'

services:
  runner:
    build: ./build
    # image: gitlab/gitlab-runner
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Linux use /srv instead of /Users/Shared
      - /Users/Shared/gitlab-runner/config:/etc/gitlab-runner:rw
    networks:
      - gitlab-runner

networks:
  gitlab-runner:
    external: false