version: '3.8'

services:
  runner:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: example/gitlab-runner:1.0
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Linux use /srv instead of /Users/Shared
      - /Users/Shared/gitlab-runner/config:/etc/gitlab-runner:rw
    networks:
      - ci

networks:
  ci:
    external: false
    name: ci