version: "3"

services:
  runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Linux use /srv instead of /Users/Shared
      - /Users/Shared/gitlab-runner/config:/etc/gitlab-runner
    networks:
      - gitlab-runner-net

  hexo:
    image: blog-hexo:next
    container_name: hexo
    restart: always
    ports:
      - "4000:4000"
      - "4001:22"
    environment:
      - PASSWORD=password
      - PUB_KEY=
    networks:
      - gitlab-runner-net


networks:
  gitlab-runner-net:
