version: "3.9"

services:
  acme:
    image: neilpang/acme.sh:3.0.2
    networks:
      - host
    volumes:
      - acme_data:/acme.sh:rw
    working_dir: /acme.sh
    command: [ 'daemon' ]
    #command: source /run/secrets/acme_cloud_flare_env
    #command: acme.sh --register-account -m $CF_Email --issue -k ec-256 --dns dns_cf -d *.example.online
    #command: acme.sh --installcert --ecc -d *.example.online --fullchain-file /etc/ssl/wildcard-certificate.crt --key-file /etc/ssl/wildcard-certificate.key
    secrets:
      - source: acme_cloud_flare_env
        mode: 0600
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

  nginx:
    image: nginx:1.20.2
    ports:
      - published: 80
        target: 80
        protocol: tcp
        mode: host
      - published: 443
        target: 443
        protocol: tcp
        mode: host
    networks:
      - host
    volumes:
      - nginx_log:/var/log/nginx:rw
    working_dir: /var/www
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == California-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"
    configs:
      - source: nginx_htpasswd
        target: /etc/nginx/.htpasswd
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_bark
        target: /etc/nginx/conf.d/service.d/bark.conf
      - source: nginx_blog
        target: /etc/nginx/conf.d/service.d/blog.conf
      - source: nginx_docker_registry
        target: /etc/nginx/conf.d/service.d/docker_registry.conf
      - source: nginx_elasticsearch
        target: /etc/nginx/conf.d/service.d/elasticsearch.conf
      - source: nginx_frps
        target: /etc/nginx/conf.d/service.d/frps.conf
      - source: nginx_gitlab
        target: /etc/nginx/conf.d/service.d/gitlab.conf
      - source: nginx_kibana
        target: /etc/nginx/conf.d/service.d/kibana.conf
      - source: nginx_minio
        target: /etc/nginx/conf.d/service.d/minio.conf
      - source: nginx_portainer
        target: /etc/nginx/conf.d/service.d/portainer.conf
      - source: nginx_qinglong
        target: /etc/nginx/conf.d/service.d/qinglong.conf
      - source: nginx_rabbitmq
        target: /etc/nginx/conf.d/service.d/rabbit.conf
      - source: nginx_shadowsocks
        target: /etc/nginx/conf.d/service.d/shadowsocket.conf
      - source: nginx_swagger
        target: /etc/nginx/conf.d/service.d/swagger.conf
      - source: nginx_vscode
        target: /etc/nginx/conf.d/service.d/vscode.conf
      - source: nginx_prometheus
        target: /etc/nginx/conf.d/service.d/prometheus.conf
    secrets:
      - source: wildcard-certificate.crt
        target: /etc/ssl/wildcard-certificate.crt
        mode: 0600
      - source: wildcard-certificate.key
        target: /etc/ssl/wildcard-certificate.key
        mode: 0600

configs:
  nginx_htpasswd:
    name: nginx_htpasswd_v1
    file: ./conf/.htpasswd
  nginx_config:
    name: nginx_config_v1
    file: ./conf/nginx.conf
  nginx_default_config:
    name: nginx_default_config_v1
    file: ./conf/conf.d/default.conf
  nginx_bark:
    name: nginx_bark_v1
    file: ./conf/conf.d/service.d/bark.conf
  nginx_blog:
    name: nginx_blog_v1
    file: ./conf/conf.d/service.d/blog.conf
  nginx_docker_registry:
    name: nginx_docker_registry_v1
    file: ./conf/conf.d/service.d/docker_registry.conf
  nginx_elasticsearch:
    name: nginx_elasticsearch_v1
    file: ./conf/conf.d/service.d/elasticsearch.conf
  nginx_frps:
    name: nginx_frps_v1
    file: ./conf/conf.d/service.d/frps.conf
  nginx_gitlab:
    name: nginx_gitlab_v1
    file: ./conf/conf.d/service.d/gitlab.conf
  nginx_kibana:
    name: nginx_kibana_v1
    file: ./conf/conf.d/service.d/kibana.conf
  nginx_minio:
    name: nginx_minio_v1
    file: ./conf/conf.d/service.d/minio.conf
  nginx_portainer:
    name: nginx_portainer_v1
    file: ./conf/conf.d/service.d/portainer.conf
  nginx_qinglong:
    name: nginx_qinglong_v1
    file: ./conf/conf.d/service.d/qinglong.conf
  nginx_rabbitmq:
    name: nginx_rabbitmq_v1
    file: ./conf/conf.d/service.d/rabbit.conf
  nginx_shadowsocks:
    name: nginx_shadowsocks_v1
    file: ./conf/conf.d/service.d/shadowsocket.conf
  nginx_swagger:
    name: nginx_swagger_v1
    file: ./conf/conf.d/service.d/swagger.conf
  nginx_vscode:
    name: nginx_vscode_v1
    file: ./conf/conf.d/service.d/vscode.conf
  nginx_prometheus:
    name: nginx_prometheus_v1
    file: ./conf/conf.d/service.d/prometheus.conf

secrets:
  acme_cloud_flare_env:
    name: acme_cloud_flare_env_v1
    file: ./conf/acme/acme_cloud_flare_env.sh
  wildcard-certificate.crt:
    name: wildcard_certificate_crt_v3
    file: ./conf/ssl/wildcard-certificate.crt
  wildcard-certificate.key:
    name: wildcard_certificate_key_v3
    file: ./conf/ssl/wildcard-certificate.key

volumes:
  acme_data:
    name: acme_data
    driver: local
  nginx_log:
    name: nginx_log
    driver: local

networks:
  host:
    name: host
    external: true