version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    working_dir: /var/www
    volumes:
      - ./conf/ssl/:/etc/nginx/ssl/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d/:/etc/nginx/conf.d/:ro
      - ./log/:/var/log/nginx/:rw
    networks:
      - develop

networks:
  develop:
    external: false
    name: develop