version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    working_dir: /var/www
    volumes:
      - ./conf/ssl:/etc/ssl:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./conf/conf.d/:/etc/nginx/conf.d/:rw
      - filebeat:/var/log:rw
    networks:
      - develop

networks:
  develop:
    external: true

volumes:
  filebeat:
    name: filebeat
    external: true