version: "3.9"

services:
  acme:
    image: neilpang/acme.sh:3.0.2
    networks:
      - host
    volumes:
      - acme_data:/acme.sh:rw
    working_dir: /acme.sh
    command: [ 'daemon' ]
    #command: source /run/secrets/acme_cloud_flare_env
    #command: acme.sh --register-account -m $CF_Email --issue -k ec-256 --dns dns_cf -d *.example.online
    #command: acme.sh --installcert --ecc -d *.example.online --fullchain-file /etc/ssl/wildcard-certificate.crt --key-file /etc/ssl/wildcard-certificate.key
    secrets:
      - source: acme_cloud_flare_env
        mode: 0600
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    environment:
      TZ: "Asia/Shanghai"

  nginx:
    image: nginx:1.20.2
    ports:
      - published: 80
        target: 80
        protocol: tcp
        mode: host
      - published: 443
        target: 443
        protocol: tcp
        mode: host
    networks:
      - host
    volumes:
      - nginx_log:/var/log/nginx:rw
      - nginx_configs:/etc/nginx/conf.d/service.d:rw
    working_dir: /var/www
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == California-CentOS
          - node.platform.os == linux
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    environment:
      TZ: "Asia/Shanghai"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    secrets:
      - source: nginx_htpasswd
        target: /etc/nginx/.htpasswd
        mode: 0600
      - source: wildcard-certificate.crt
        target: /etc/ssl/wildcard-certificate.crt
        mode: 0600
      - source: wildcard-certificate.key
        target: /etc/ssl/wildcard-certificate.key
        mode: 0600
      - source: outer-certificate.crt
        target: /etc/ssl/outer-certificate.crt
        mode: 0600
      - source: outer-certificate.key
        target: /etc/ssl/outer-certificate.key
        mode: 0600

configs:
  nginx_config:
    name: nginx_config_v1
    file: ./conf/nginx.conf

secrets:
  nginx_htpasswd:
    name: nginx_htpasswd_v1
    file: ./conf/.htpasswd
  acme_cloud_flare_env:
    name: acme_cloud_flare_env_v1
    file: ./conf/acme/acme_cloud_flare_env.sh
  wildcard-certificate.crt:
    name: wildcard_certificate_crt_v3
    file: ./conf/ssl/wildcard-certificate.crt
  wildcard-certificate.key:
    name: wildcard_certificate_key_v3
    file: ./conf/ssl/wildcard-certificate.key
  outer-certificate.crt:
    name: outer_certificate_crt_v3
    file: ./conf/ssl/outer-certificate.crt
  outer-certificate.key:
    name: outer_certificate_key_v3
    file: ./conf/ssl/outer-certificate.key

volumes:
  acme_data:
    name: acme_data
    driver: local
  nginx_log:
    name: nginx_log
    driver: local
  nginx_configs:
    name: nginx_configs
    driver_opts:
      type: none
      o: bind
      device: /home/docker/docker/Nginx/conf/conf.d/service.d

networks:
  host:
    name: host
    external: true