version: "3.9"

services:
  frps:
    image: fatedier/frps:v0.51.0
    networks:
      - host
    volumes:
      - frps_log:/var/log/frp
    command:
      - -c
      - /etc/frp/frps.ini
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    environment:
      TZ: "Asia/Shanghai"
    configs:
      - source: frps_config
        target: /etc/frp/frps.ini

configs:
  frps_config:
    name: frps_config_v1
    file: ./conf/server/frps.ini

volumes:
  frps_log:
    name: frps_log
    external: false

networks:
  host:
    name: host
    external: true