version: "3.9"

services:
  frps:
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        FRP_VERSION: ${FRP_VERSION}
        OS: ${OS:-linux}
        ARCH: ${ARCH:-amd64}
    image: example:frps
    network_mode: host
    command: /usr/bin/frps -c /etc/frp/frps.ini
    volumes:
      - ./conf/frps.ini:/etc/frp/frps.ini:rw
      - ./log:/var/log/frp

  frpc:
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        FRP_VERSION: ${FRP_VERSION}
        OS: ${OS:-linux}
        ARCH: ${ARCH:-amd64}
    image: example:frpc
    command: /usr/bin/frpc -c /etc/frp/frpc.ini
    volumes:
      - ./conf/frpc.ini:/etc/frp/frpc.ini:rw
      - ./log:/var/log/frp