version: "3.9"

services:
  frps:
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        FRP_VERSION: ${FRP_VERSION:-0.35.1}
        OS: ${OS:-linux}
        ARCH: ${ARCH:-amd64}
    image: registry.***REMOVED***/example/frps:1.0
    container_name: frps
    restart: always
    network_mode: host
    command: /usr/bin/frps -c /etc/frp/frps.ini
    volumes:
      - ./conf/frps.ini:/etc/frp/frps.ini:rw
      - ./log:/var/log/frp

  frpc:
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        FRP_VERSION: ${FRP_VERSION:-0.35.1}
        OS: ${OS:-linux}
        ARCH: ${ARCH:-amd64}
    image: registry.***REMOVED***/example/frpc:1.0
    container_name: frpc
    restart: always
    command: /usr/bin/frpc -c /etc/frp/frpc.ini
    volumes:
      - ./conf/frpc.ini:/etc/frp/frpc.ini:rw
      - ./log:/var/log/frp