version: "3.9"

services:
  bark-server:
    image: finab/bark-server:v2.0.1
    ports:
      - published: 58084
        target: 8080
    networks:
      - cluster
    volumes:
      - bark_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux

volumes:
  bark_data:
    name: bark_data

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true