version: "3.9"

services:
  bark-server:
    image: finab/bark-server:${BARK_VERSION:-v2.1.5}
    container_name: bark
    restart: always
    ports:
      - "58084:8080"
    networks:
      - develop
    volumes:
      - /media/psf/Docker/Bark/data:/data
      - /media/psf/Docker/Bark/conf/localtime:/etc/localtime

  prometheus-webhook:
    image: banjintaohua/eggplant:1.1
    container_name: prometheus-webhook
    restart: always
    ports:
      - "59094:59094"
    networks:
      - develop
    volumes:
      - /media/psf/Go/eggplant/config/config.ini:/etc/eggplant/config.ini:rw

networks:
  develop:
    name: develop
    external: true