version: "3.9"

services:
  bark-server:
    image: finab/bark-server:${BARK_VERSION:-latest}
    container_name: bark
    restart: always
    ports:
      - "58084:8080"
    networks:
      - develop
    volumes:
      - ./data:/data

networks:
  develop:
    name: develop
    external: true