version: "3.9"

services:
  bark-server:
    image: finab/bark-server:${BARK_VERSION:-v2.1.5}
    container_name: bark
    restart: always
    ports:
      - "58084:8080"
    networks:
      - develop
    volumes:
      - /media/psf/Docker/Bark/data:/data
      - /media/psf/Docker/Bark/conf/localtime:/etc/localtime

networks:
  develop:
    name: develop
    external: true