version: "3.7"

services:

  elasticsearch:
    build:
      context: ./build/elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/extensions:/home/extensions:ro
      - elasticsearch-data:/usr/share/elasticsearch/data:rw
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk

  logstash:
    build:
      context: ./build/logstash
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - logstash-data:/usr/share/logstash/data:rw
    ports:
      - "5000:5000"
      - "9600:9600"
      - "60030:60030"
    restart: always
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./build/kibana
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
      - kibana-data:/usr/share/kibana/data:rw
    ports:
      - "5601:5601"
    restart: always
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16

volumes:
  elasticsearch-data:
  logstash-data:
  kibana-data: