version: "3.9"

services:
  python:
    image: example/golang:1.17.3-dlv
    working_dir: /release
    ports:
      - "52345:2345"
      - "58086:8080"
    networks:
      - cluster
    command: [ "run" ]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true