version: "3.9"

services:
  python:
    image: banjintaohua/python-3.9:fastapi
    working_dir: /var/www/peach
    ports:
      - "58085:8080"
    networks:
      - cluster
    volumes:
      - nfs_data:/var/www/python:rw
    command: [ "run" ]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

volumes:
  nfs_data:
    name: nfs_data
    driver_opts:
      type: "nfs"
      o: "addr=nfs.example.com,nolock,soft,rw"
      device: ":/nfs/share"

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true