version: '3.8'

services:
  python:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: example/python-39:1.0
    container_name: python-39
    restart: always
    ports:
      - 9006:8080
    networks:
      - develop
    command: tail -f /dev/null

networks:
  develop:
    external: true