version: "3.9"

services:
  python:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: example/python-3.9:1.0
    ports:
      - "9006:8080"
    networks:
      - develop
    command: tail -f /dev/null

networks:
  develop:
    external: true