version: "3.7"

services:
  python:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: example/python-3.9:1.0
    container_name: python-3.9
    restart: always
    ports:
      - "9006:8080"
    networks:
      - develop
    command: tail -f /dev/null

networks:
  develop:
    external: true