version: "3.9"

services:
  python:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: example/python-3.9:fastapi
    container_name: python-3.9
    working_dir: /var/www/app
    restart: always
    ports:
      - "58085:8080"
    networks:
      - develop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/" ]
      interval: 30s
      timeout: 20s
      retries: 3
    command: tail -f /dev/null
    # command: [ "run" ]
    volumes:
      - ../../Python/***REMOVED***:/var/www/app:rw
    environment:
      TZ: "Asia/Shanghai"

networks:
  develop:
    external: true