version: "3.9"

services:
  python:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: registry.example.online/example/python-3.9:scratch
    container_name: python-3.9
    working_dir: /var/www/app
    restart: always
    ports:
      - "63828:8080"
    networks:
      - develop
    command: tail -f /dev/null
    volumes:
      - ../../Python/***REMOVED***:/var/www/app:rw

networks:
  develop:
    external: true