version: "3.9"

services:
  python:
    image: registry.example.online/example/python-3.9:fastapi
    working_dir: /var/www/app
    ports:
      - "58085:8080"
    networks:
      - cluster
    volumes:
      - ./data/fastapi:/var/www/app:rw
    command: [ "run" ]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true