version: "3.9"

services:
  python:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: registry.***REMOVED***/example/python-3.9:scratch
    container_name: python-3.9
    restart: always
    ports:
      - "9006:8080"
    networks:
      - develop
    command: tail -f /dev/null

networks:
  develop:
    external: true