version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:2.18.4
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - published: 59000
        target: 9000
        protocol: tcp
        mode: host
      - published: 8000
        target: 8000
        protocol: tcp
        mode: host
    networks:
      - cluster
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
          - node.hostname == ShangHai-CentOS
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M

  agent:
    image: portainer/agent:2.18.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - published: 59001
        target: 9001
        protocol: tcp
        mode: host
    networks:
      - cluster
    deploy:
      mode: global
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.platform.os == linux
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M

volumes:
  portainer_data:
    name: portainer_data

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: false
