version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:2.6.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "59000:9000"
      - "8000:8000"
    extra_hosts:
      - docker-daemon-vmware:***REMOVED***
      - docker-daemon-bandwagon:***REMOVED***
    networks:
      - portainer_agent_network
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
          - node.hostname == GuangZhou-CentOS

  agent:
    image: portainer/agent:2.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent_network
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux
          - node.hostname != California-CentOS

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer_agent_network:
    name: portainer_agent_network
    driver: overlay
    attachable: true
    external: false
