version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:2.6.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - target: 9000
        published: 59000
        protocol: tcp
        mode: host
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    extra_hosts:
      - docker-daemon-vmware:***REMOVED***
      - docker-daemon-bandwagon:***REMOVED***
    networks:
      - cluster
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
          - node.hostname == ShangHai-CentOS

  agent:
    image: portainer/agent:2.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 59001
        protocol: tcp
        mode: host
    networks:
      - cluster
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux

volumes:
  portainer_data:
    name: portainer_data

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: false
