version: "3.9"

services:
  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - "63818:9000"
      - "8000:8000"
    extra_hosts:
      - docker-daemon-vmware:***REMOVED***
      - docker-daemon-bandwagon:***REMOVED***
    networks:
      - portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == Cloud

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    networks:
      - portainer
    ports:
      - target: 9001
        published: 63820
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux
          - node.hostname != Cloud
          - node.hostname != Bandwagon

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer:
    name: portainer
    driver: overlay
    attachable: true
    external: false
