version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION:-2.18.4}
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    restart: "no"
    ports:
      - "59000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      develop:
        ipv4_address: 172.19.0.35

  portainer-edge-agent:
    image: portainer/agent:2.18.4
    container_name: portainer-edge-agent
    restart: "no"
    environment:
      EDGE: 1
      EDGE_ID: ${EDGE_ID}
      EDGE_KEY: ${EDGE_KEY}
    ports:
      - "59001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer_agent_data:/data
    networks:
      - develop

volumes:
  portainer_data:
    name: portainer_data
  portainer_agent_data:
    name: portainer_agent_data

networks:
  develop:
    name: develop
    external: true
