version: '3.5'

services:
  db:
    image: mysql:5.6
    command: mysqld
    container_name: mysql-56
    restart: always
    volumes:
      - ./data/:/var/lib/mysql:rw
      - ./conf/:/etc/mysql/conf.d:rw
      - ./logs/:/var/log/mysql/:rw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

networks:
  default:
    external:
      name: develop
