version: "3.7"

services:
  db:
    image: mysql:5.6
    command: mysqld
    container_name: mysql-56
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3306:3306"
    volumes:
      - ./data/:/var/lib/mysql:rw
      - ./conf/:/etc/mysql/conf.d:rw
      - ./log/:/var/log/mysql/:rw
    networks:
      - develop
    environment:
      - MYSQL_ROOT_PASSWORD=password

networks:
  develop:
    external: true
