version: "3.9"

services:
  db:
    image: mysql:5.6
    volumes:
      - mysql-56:/var/lib/mysql:rw
      - mysql-56:/etc/mysql/conf.d:rw
      - mysql-56:/var/log/mysql/:rw
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-56
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - 'node.role == worker'

networks:
  mysql-56:
    name: mysql-56
    driver: overlay

volumes:
  mysql-56:
    name: mysql-56
    driver: local