version: "3.9"

services:
  mysql:
    image: mysql:8.0.37
    ports:
      - published: 53306
        target: 3306
        protocol: tcp
        mode: host
    working_dir: /var/lib/mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql:rw
      - mysql_local_configs:/etc/mysql/conf.d:rw
    configs:
      - source: mysql_config
        target: /etc/my.cnf
    secrets:
      - source: mysql_root_password
        mode: 0600
      - source: mysql_root_host
        mode: 0600
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_ROOT_HOST_FILE: /run/secrets/mysql_root_host
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != California-CentOS
          - node.platform.os == linux

configs:
  mysql_config:
    name: mysql_config_v1
    file: ./conf/mysql/my.cnf

secrets:
  mysql_root_host:
    name: mysql_root_host_v1
    file: ./conf/secrets/mysql_root_host.txt
  mysql_root_password:
    name: mysql_root_password_v1
    file: ./conf/secrets/mysql_root_password.txt

volumes:
  mysql_local_configs:
    name: mysql_local_configs
    driver: local
    external: false

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true