version: "3.9"

services:
  ss-client:
    image: teddysun/shadowsocks-libev:${SHADOWSOCKS_VERSION:-3.3.5}
    command: "ss-local -c /etc/shadowsocks-libev/config.json 2>&1"
    working_dir: /etc/shadowsocks-libev
    networks:
      - host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    configs:
      - source: shadowsocks_client
        target: /etc/shadowsocks-libev/config.json
    environment:
      TZ: "Asia/Shanghai"

  ss-websocket-http:
    image: teddysun/shadowsocks-libev:${SHADOWSOCKS_VERSION:-3.3.5}
    command: "ss-server -c /etc/shadowsocks-libev/config.json 2>&1"
    working_dir: /etc/shadowsocks-libev
    networks:
      - cluster
    ports:
      - published: 51080
        target: 51080
        protocol: tcp
        mode: host
      - published: 51080
        target: 51080
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == California-CentOS
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    configs:
      - source: shadowsocks_libev_over_http_config
        target: /etc/shadowsocks-libev/config.json
    environment:
      TZ: "Asia/Shanghai"

  ss-websocket-https:
    image: teddysun/shadowsocks-libev:${SHADOWSOCKS_VERSION:-3.3.5}
    command: "ss-server -c /etc/shadowsocks-libev/config.json 2>&1"
    working_dir: /etc/shadowsocks-libev
    networks:
      - cluster
    ports:
      - published: 51081
        target: 51081
        protocol: tcp
        mode: host
      - published: 51081
        target: 51081
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == California-CentOS
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    configs:
      - source: shadowsocks_libev_over_https_config
        target: /etc/shadowsocks-libev/config.json
    secrets:
      - source: outer-certificate.crt
        target: /etc/ssl/outer-certificate.crt
        mode: 0600
      - source: outer-certificate.key
        target: /etc/ssl/outer-certificate.key
    environment:
      TZ: "Asia/Shanghai"

configs:
  shadowsocks_libev_over_http_config:
    name: shadowsocks_libev_over_http_config_v1
    file: ./conf/ss-websocket-http/config.json
  shadowsocks_libev_over_https_config:
    name: shadowsocks_libev_over_https_config_v2
    file: ./conf/ss-websocket-https/config.json
  shadowsocks_client:
    name: shadowsocks_client_v1
    file: ./conf/ss-client/config.json

secrets:
  outer-certificate.crt:
    name: outer_certificate_crt_v1
    external: true
  outer-certificate.key:
    name: outer_certificate_key_v1
    external: true

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true
  host:
    name: host
    external: true