version: "3.9"

services:
  ss-client:
    image: shadowsocks/shadowsocks-libev:${SHADOWSOCKS_VERSION:-v3.3.5}
    container_name: ss-client
    command: "/usr/bin/ss-local -c /etc/shadowsocks-libev/config.json"
    working_dir: /etc/shadowsocks-libev
    network_mode: host
    restart: always
    volumes:
      - ./conf/ss-client/config.json:/etc/shadowsocks-libev/config.json:rw
      - ./conf/ss-client/v2ray-plugin:/usr/local/bin/v2ray-plugin:ro
      - ./log/ss-client:/var/log/shadowsocks

  ss-websocket-http:
    image: teddysun/shadowsocks-libev:${SHADOWSOCKS_VERSION:-3.3.5}
    container_name: ss-websocket-http
    command: "ss-server -c /etc/shadowsocks-libev/config.json > /var/log/ss-websocket-http.log 2>&1"
    working_dir: /etc/shadowsocks-libev
    networks:
      - vpn
    restart: always
    ports:
      - "63821:9100"
      - "63821:9100/udp"
    volumes:
      - ./conf/ss-websocket-http:/etc/shadowsocks-libev:rw
      - ./log/ss-websocket-http:/var/log/shadowsocks

  ss-websocket-https:
    image: teddysun/shadowsocks-libev:${SHADOWSOCKS_VERSION:-3.3.5}
    container_name: ss-websocket-https
    command: "ss-server -c /etc/shadowsocks-libev/config.json > /var/log/ss-websocket-https 2>&1"
    working_dir: /etc/shadowsocks-libev
    networks:
      - vpn
    restart: always
    ports:
      - "63822:9100"
      - "63822:9100/udp"
    volumes:
      - ../Nginx/conf/ssl:/etc/ssl:ro
      - ./conf/ss-websocket-https:/etc/shadowsocks-libev:rw
      - ./log/ss-websocket-https:/var/log/shadowsocks

networks:
  vpn:
    name: develop
    external: false
    driver: bridge