version: "3.9"

services:
  ss-websocket-http:
    image: teddysun/shadowsocks-libev:3.3.5
    command: "ss-server -c /etc/shadowsocks-libev/config.json > /var/log/ss-websocket-http.log 2>&1"
    working_dir: /etc/shadowsocks-libev
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.oversea == true
    networks:
      - cluster
    ports:
      - "9001:9000"
      - "9001:9000/udp"
    volumes:
      - ./conf/ss-websocket-http:/etc/shadowsocks-libev:rw
      - ./log/ss-websocket-http:/var/log/shadowsocks

  ss-websocket-https:
    image: teddysun/shadowsocks-libev:3.3.5
    command: "ss-server -c /etc/shadowsocks-libev/config.json > /var/log/ss-websocket-https 2>&1"
    working_dir: /etc/shadowsocks-libev
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.oversea == true
    networks:
      - cluster
    ports:
      - "9002:9000"
      - "9002:9000/udp"
    volumes:
      - ../Nginx/conf/ssl:/etc/ssl:ro
      - ./conf/ss-websocket-https:/etc/shadowsocks-libev:rw
      - ./log/ss-websocket-https:/var/log/shadowsocks

networks:
  cluster:
    name: cluster
    external: true
    driver: overlay