version: "3.9"

services:
  ss-websocket-http:
    image: teddysun/shadowsocks-libev:${SHADOWSOCKS_VERSION:-3.3.5}
    command: "ss-server -c /etc/shadowsocks-libev/config.json 2>&1"
    working_dir: /etc/shadowsocks-libev
    networks:
      - cluster
    ports:
      - published: 51080
        target: 51080
        protocol: tcp
        mode: host
      - published: 51080
        target: 51080
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == California-CentOS
    configs:
      - source: ss-websocket-http-config
        target: /etc/shadowsocks-libev/config.json
        mode: 0644

  ss-websocket-https:
    image: teddysun/shadowsocks-libev:${SHADOWSOCKS_VERSION:-3.3.5}
    command: "ss-server -c /etc/shadowsocks-libev/config.json 2>&1"
    working_dir: /etc/shadowsocks-libev
    networks:
      - cluster
    ports:
      - published: 51081
        target: 51081
        protocol: tcp
        mode: host
      - published: 51081
        target: 51081
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == California-CentOS
    configs:
      - source: ss-websocket-https-config
        target: /etc/shadowsocks-libev/config.json
    secrets:
      - source: wildcard-certificate.crt
        target: /etc/ssl/wildcard-certificate.crt
        mode: 0600
      - source: wildcard-certificate.key
        target: /etc/ssl/wildcard-certificate.key
        mode: 0600

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true

configs:
  ss-cliennt-config:
    external: true
  ss-websocket-http-config:
    external: true
  ss-websocket-https-config:
    external: true

secrets:
  wildcard-certificate.crt:
    name: wildcard-certificate.crt.v2
    external: true
  wildcard-certificate.key:
    name: wildcard-certificate.key.v2
    external: true