version: "3.9"

services:
  ss-client:
    image: shadowsocks/shadowsocks-libev:v3.3.5
    container_name: ss-client
    command: "/usr/bin/ss-local -c /etc/shadowsocks-libev/config.json 2>&1"
    working_dir: /etc/shadowsocks-libev
    network_mode: host
    restart: always
    volumes:
      - /media/psf/Docker/Shadowsocks/log/ss-client:/var/log/shadowsocks
      - /media/psf/Docker/Shadowsocks/conf/ss-client/config.json:/etc/shadowsocks-libev/config.json:rw
      - /media/psf/Docker/Shadowsocks/conf/ss-client/v2ray-plugin:/usr/local/bin/v2ray-plugin:ro
    environment:
      TZ: "Asia/Shanghai"

  ss-websocket-http:
    image: teddysun/shadowsocks-libev:${SHADOWSOCKS_VERSION:-3.3.5}
    container_name: ss-websocket-http
    command: "ss-server -c /etc/shadowsocks-libev/config.json > /var/log/ss-websocket-http.log 2>&1"
    working_dir: /etc/shadowsocks-libev
    networks:
      - vpn
    restart: always
    ports:
      - "51080:51080"
      - "51080:51080/udp"
    volumes:
      - /media/psf/Docker/Shadowsocks/log/ss-websocket-http:/var/log/shadowsocks
      - /media/psf/Docker/Shadowsocks/conf/ss-websocket-http:/etc/shadowsocks-libev:rw
    environment:
      TZ: "Asia/Shanghai"

  ss-websocket-https:
    image: teddysun/shadowsocks-libev:${SHADOWSOCKS_VERSION:-3.3.5}
    container_name: ss-websocket-https
    command: "ss-server -c /etc/shadowsocks-libev/config.json > /var/log/ss-websocket-https 2>&1"
    working_dir: /etc/shadowsocks-libev
    networks:
      - vpn
    restart: always
    ports:
      - "51081:51081"
      - "51081:51081/udp"
    volumes:
      - /media/psf/Docker/Shadowsocks/log/ss-websocket-https:/var/log/shadowsocks
      - /media/psf/Docker/Shadowsocks/conf/ss-websocket-https:/etc/shadowsocks-libev:rw
      - /media/psf/Docker/Nginx/conf/ssl:/etc/ssl:ro
    environment:
      TZ: "Asia/Shanghai"

networks:
  vpn:
    name: develop
    external: false
    driver: bridge