version: "3.9"

services:
  elasticsearch:
    build:
      context: ./build/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    restart: "no"
    volumes:
      - /media/psf/Docker/ElasticStack/conf/localtime:/etc/localtime
      - /media/psf/Docker/ElasticStack/conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "59200:9200"
      - "59300:9300"
    deploy:
      resources:
        limits:
          memory: 2G
    mem_swappiness: 0
    environment:
      ES_JAVA_OPTS: "-Xmx2048m -Xms256m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD-changeme}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - develop

  logstash:
    build:
      context: ./build/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    restart: "no"
    volumes:
      - /media/psf/Docker/ElasticStack/conf/localtime:/etc/localtime
      - /media/psf/Docker/ElasticStack/conf/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /media/psf/Docker/ElasticStack/conf/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "55044:5044"
      - "55000:5000/tcp"
      - "55000:5000/udp"
      - "59600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms256m"
    networks:
      - develop
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./build/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    restart: "no"
    volumes:
      - /media/psf/Docker/ElasticStack/conf/localtime:/etc/localtime
      - /media/psf/Docker/ElasticStack/conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "55601:5601"
    networks:
      - develop
    depends_on:
      - elasticsearch

networks:
  develop:
    name: develop
    driver: bridge
    external: true

volumes:
  elasticsearch_data:
    name: elasticsearch_data
    external: false
