version: "3.9"

services:
  hexo:
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
    image: registry.banjintaohua.xyz/banjintaohua/notes:2.1
    container_name: hexo
    restart: always
    ports:
      - "54000:4000"
      - "50023:22"
    environment:
      TZ: "Asia/Shanghai"
      REMOTE_URL: ${REMOTE_URL}
      BRANCH: ${BRANCH:-master}
      HEXO_DEBUG: ${HEXO_DEBUG}
    working_dir: /usr/local/opt/hexo/blog/source/_posts
    volumes:
      - /media/psf/Docker/Hexo/conf/_config.yml:/usr/local/opt/hexo/blog/_config.yml:rw
      - /media/psf/Docker/Hexo/conf/next/_config.yml:/usr/local/opt/hexo/blog/themes/next/_config.yml:rw
      - /media/psf/Docker/Hexo/conf/next/Pisces.styl:/usr/local/opt/hexo/blog/themes/next/source/css/_variables/Pisces.styl:rw
      - /media/psf/Docker/Hexo/conf/next/zh-CN.yml:/usr/local/opt/hexo/blog/themes/next/languages/zh-CN.yml:rw
      - /media/psf/Docker/Hexo/conf/ssh/id_rsa:/root/.ssh/id_rsa:rw
      - /media/psf/Docker/Hexo/conf/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:rw
      - /media/psf/Docker/Hexo/conf/ssh/authorized_keys:/root/.ssh/authorized_keys:rw
    networks:
      - develop

networks:
  develop:
    external: true