version: "3.9"

services:
  hexo:
    image: registry.example.online/example/notes:2.1
    ports:
      - "54000:4000"
      - "57892:22"
    environment:
      REMOTE_URL: ${REMOTE_URL:-git@github.com:example/notes.git}
      BRANCH: ${BRANCH:-master}
      HEXO_DEBUG: ${HEXO_DEBUG}
    working_dir: /usr/local/opt/hexo/blog/source/_posts
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.platform.os == linux
          - node.hostname != California-CentOS
    configs:
      - source: hexo_config_yml
        target: /usr/local/opt/hexo/blog/_config.yml
      - source: hexo_next_config_yml
        target: /usr/local/opt/hexo/blog/themes/next/_config.yml
      - source: hexo_next_Pisces_styl
        target: /usr/local/opt/hexo/blog/themes/next/source/css/_variables/Pisces.styl
      - source: hexo_next_zh_CN_yml
        target: /usr/local/opt/hexo/blog/themes/next/languages/zh-CN.yml
    secrets:
      - source: hexo_ssh_authorized_keys
        target: /root/.ssh/authorized_keys
        mode: 0600
      - source: hexo_ssh_id_rsa
        target: /root/.ssh/id_rsa
        mode: 0600
      - source: hexo_ssh_id_rsa_pub
        target: /root/.ssh/id_rsa.pub
        mode: 0600
    networks:
      - cluster

configs:
  hexo_config_yml:
    name: hexo_config_yml_v1
    external: false
    file: ./conf/_config.yml
  hexo_next_config_yml:
    name: hexo_next_config_yml_v1
    external: false
    file: ./conf/next/_config.yml
  hexo_next_Pisces_styl:
    name: hexo_next_Pisces_styl_v1
    external: false
    file: ./conf/next/Pisces.styl
  hexo_next_zh_CN_yml:
    name: hexo_next_zh_CN_yml_v1
    external: false
    file: ./conf/next/zh-CN.yml

secrets:
  hexo_ssh_authorized_keys:
    name: hexo_ssh_authorized_keys
    external: false
    file: ./conf/ssh/authorized_keys
  hexo_ssh_id_rsa:
    name: hexo_ssh_id_rsa
    external: false
    file: ./conf/ssh/id_rsa
  hexo_ssh_id_rsa_pub:
    name: hexo_ssh_id_rsa_pub
    external: false
    file: ./conf/ssh/id_rsa.pub

networks:
  cluster:
    name: cluster
    driver: overlay
    external: true