version: "3.9"

services:
  hexo:
    image: registry.***REMOVED***/example/notes:1.5
    ports:
      - "54000:4000"
      - "54022:22"
    environment:
      REMOTE_URL: ${REMOTE_URL:-git@github.com:example/notes.git}
      BRANCH: ${BRANCH:-master}
      HEXO_DEBUG: ${HEXO_DEBUG}
    working_dir: /usr/local/opt/hexo/blog/source/_posts
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux
          - node.hostname == GuangZhou-CentOS
    command:
      - sh
      - -c
      - |
        test -d /usr/local/opt/hexo/blog/source/_posts/.git || git clone --progress $${REMOTE_URL} /usr/local/opt/hexo/blog/source/_posts
        rm -f /usr/local/opt/hexo/blog/source/_posts/package.json
        cd /usr/local/opt/hexo/blog/source
        /usr/local/bin/hexo clean
        /usr/local/bin/hexo generate $${HEXO_DEBUG}
        nohup /usr/local/bin/hexo server 2>&1 &
        /usr/sbin/sshd -D
    configs:
      - source: hexo-_config.yml
        target: /usr/local/opt/hexo/blog/_config.yml
      - source: hexo-next-_config.yml
        target: /usr/local/opt/hexo/blog/themes/next/_config.yml
      - source: hexo-next-Pisces.styl
        target: /usr/local/opt/hexo/blog/themes/next/source/css/_variables/Pisces.styl
      - source: hexo-next-zh-CN.yml
        target: /usr/local/opt/hexo/blog/themes/next/languages/zh-CN.yml
    secrets:
      - source: hexo-ssh-authorized_keys
        target: /root/.ssh/authorized_keys
        mode: 0600
      - source: hexo-ssh-id_rsa
        target: /root/.ssh/id_rsa
        mode: 0600
      - source: hexo-ssh-id_rsa.pub
        target: /root/.ssh/id_rsa.pub
        mode: 0600
    networks:
      - cluster

configs:
  hexo-_config.yml:
    external: true
  hexo-next-_config.yml:
    external: true
  hexo-next-Pisces.styl:
    external: true
  hexo-next-zh-CN.yml:
    external: true

secrets:
  hexo-ssh-authorized_keys:
    external: true
  hexo-ssh-id_rsa:
    external: true
  hexo-ssh-id_rsa.pub:
    external: true

networks:
  cluster:
    name: cluster
    driver: overlay
    external: true