version: "3"

services:

  hexo:
    build: ./build
    image: blog-hexo:next
    container_name: hexo
    restart: always
    ports:
      - "4000:4000"
      - "4001:22"
    environment:
      - PASSWORD=password
      - PUB_KEY=
    volumes:
      - ./config/sshd_config:/etc/ssh/sshd_config