version: "3.9"

services:
  hexo:
    image: registry.***REMOVED***/example/notes:1.0
    ports:
      - "63825:4000"
      - "63826:22"
    environment:
      BRANCH: ${BRANCH:-master}
    working_dir: /usr/local/opt/hexo/blog/source/_posts
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux
          - node.hostname != Bandwagon
    command:
      - sh
      - -c
      - |
        /usr/local/bin/hexo server &
        /usr/sbin/sshd -D
    configs:
      - source: hexo-_config.yml
        target: /usr/local/opt/hexo/blog/_config.yml
      - source: hexo-next-_config.yml
        target: /usr/local/opt/hexo/blog/themes/next/_config.yml
      - source: hexo-next-Pisces.styl
        target: /usr/local/opt/hexo/blog/themes/next/source/css/_variables/Pisces.styl
      - source: hexo-next-zh-CN.yml
        target: /usr/local/opt/hexo/blog/themes/next/languages/zh-CN.yml
    secrets:
      - source: hexo-ssh-id_rsa
        target: /root/.ssh/id_rsa
      - source: hexo-ssh-id_rsa.pub
        target: /root/.ssh/id_rsa.pub
    networks:
      - cluster

configs:
  hexo-_config.yml:
    external: true
  hexo-next-_config.yml:
    external: true
  hexo-next-Pisces.styl:
    external: true
  hexo-next-zh-CN.yml:
    external: true

secrets:
  hexo-ssh-id_rsa:
    external: true
  hexo-ssh-id_rsa.pub:
    external: true

networks:
  cluster:
    name: cluster
    driver: overlay
    external: true