version: "3"

services:
  hexo:
    build: ./build
    image: blog-hexo:next
    container_name: hexo
    restart: always
    ports:
      - "4000:4000"
      - "4001:22"
    command:
        - sh
        - -c 
        - |
            /usr/bin/hexo server &
            /usr/sbin/sshd -D

networks:
  default:
    external:
      name: gitlab-runner