version: '3.8'

services:
  hexo:
    build:
      context: ./build/
      dockerfile: Dockerfile
      args:
        BLOG_REPOSITORY: '...'
        AUTHORIZED_KEY: ''
        BRANCH: 'master'
    image: banjintaohua/hexo:1.2
    container_name: hexo
    restart: always
    ports:
      - "4000:4000"
      - "4001:22"
    environment:
      BRANCH: 'master'
    working_dir: '/usr/local/opt/hexo/blog/source/_posts'
    command:
      # 在 yaml 中，使用 | 开头的文本块换行符都会被解析为空格
      # 等效于 dockerfile 中的 ['sh', '-c', '/usr/local/bin/hexo server & ; /usr/sbin/sshd -D']
      # sh -c '/usr/local/bin/hexo server & ; /usr/sbin/sshd -D'
      - sh
      - -c
      - |
        '
        /usr/local/bin/hexo server &
        /usr/sbin/sshd -D
        '
    volumes:
      - ./config/_config.yml:/usr/local/opt/hexo/blog/_config.yml:rw
      - ./config/next/_config.yml:/usr/local/opt/hexo/blog/themes/next/_config.yml:rw
      - ./config/next/zh-CN.yml:/usr/local/opt/hexo/blog/themes/next/languages/zh-CN.yml:rw
      - ./ssh/id_rsa:/root/.ssh/id_rsa:rw
      - ./ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:rw
    networks:
      - gitlab-runner

networks:
  gitlab-runner:
    external: true