version: "3.9"

services:
  hexo:
    build:
      context: ./build/hexo
      dockerfile: Dockerfile
      args:
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
    image: registry.***REMOVED***/example/notes:1.5
    container_name: hexo
    restart: always
    ports:
      - "63825:4000"
      - "63826:22"
    environment:
      REMOTE_URL: ${REMOTE_URL}
      BRANCH: ${BRANCH:-master}
      HEXO_DEBUG: ${HEXO_DEBUG}
    working_dir: /usr/local/opt/hexo/blog/source/_posts
    command:
      - sh
      - -c
      - |
        chmod 700 /root/.ssh
        chmod 600 /root/.ssh/authorized_keys
        chmod 600 /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa.pub
        test -d /usr/local/opt/hexo/blog/source/_posts/.git || git clone --progress $${REMOTE_URL} /usr/local/opt/hexo/blog/source/_posts
        rm -f /usr/local/opt/hexo/blog/source/_posts/package.json
        cd /usr/local/opt/hexo/blog/source
        /usr/local/bin/hexo clean
        /usr/local/bin/hexo generate $${HEXO_DEBUG}
        nohup /usr/local/bin/hexo server 2>&1 &
        /usr/sbin/sshd -D
    volumes:
      - ./conf/_config.yml:/usr/local/opt/hexo/blog/_config.yml:rw
      - ./conf/next/_config.yml:/usr/local/opt/hexo/blog/themes/next/_config.yml:rw
      - ./conf/next/Pisces.styl:/usr/local/opt/hexo/blog/themes/next/source/css/_variables/Pisces.styl:rw
      - ./conf/next/zh-CN.yml:/usr/local/opt/hexo/blog/themes/next/languages/zh-CN.yml:rw
      - ./conf/ssh/id_rsa:/root/.ssh/id_rsa:rw
      - ./conf/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:rw
      - ./conf/ssh/authorized_keys:/root/.ssh/authorized_keys:rw
    networks:
      - develop

networks:
  develop:
    external: true