version: "3.7"

services:
  hexo:
    build:
      context: ./build/
      dockerfile: Dockerfile
      args:
        BLOG_REPOSITORY: ''
        AUTHORIZED_KEY: ''
        BRANCH: 'master'
    image: example/hexo:1.3
    container_name: hexo
    restart: always
    ports:
      - "4000:4000"
      - "4001:22"
    environment:
      BRANCH: 'master'
    working_dir: '/usr/local/opt/hexo/blog/source/_posts'
    command:
      - sh
      - -c
      - |
        /usr/local/bin/hexo server &
        /usr/sbin/sshd -D
    volumes:
      - ./config/_config.yml:/usr/local/opt/hexo/blog/_config.yml:rw
      - ./config/next/_config.yml:/usr/local/opt/hexo/blog/themes/next/_config.yml:rw
      - ./config/next/Pisces.styl:/usr/local/opt/hexo/blog/themes/next/source/css/_variables/Pisces.styl:rw
      - ./config/next/zh-CN.yml:/usr/local/opt/hexo/blog/themes/next/languages/zh-CN.yml:rw
      - ./ssh/id_rsa:/root/.ssh/id_rsa:rw
      - ./ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:rw
    networks:
      - ci

networks:
  ci:
    external: true