version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    hostname: minio
    ports:
      - published: 59005
        target: 9000
        protocol: tcp
        mode: ingress
      - published: 59004
        target: 9001
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    configs:
      - source: localtime_shanghai
        target: /etc/localtime
    volumes:
      - minio_filesystem_data:/minio_filesystem_data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
    command: server /minio_filesystem_data --console-address ":9001"
    secrets:
      - source: minio_root_user
        mode: 0600
      - source: minio_root_password
        mode: 0600
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio1:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    hostname: minio1
    ports:
      - published: 59015
        target: 9000
        protocol: tcp
        mode: ingress
      - published: 59014
        target: 9001
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    configs:
      - source: localtime_shanghai
        target: /etc/localtime
    volumes:
      - minio_erasure_code_data_1:/minio_erasure_code_data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
    command: server http://minio{1...3}/minio_erasure_code_data --console-address ":9001"
    secrets:
      - source: minio_root_user
        mode: 0600
      - source: minio_root_password
        mode: 0600
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    hostname: minio2
    ports:
      - published: 59025
        target: 9000
        protocol: tcp
        mode: ingress
      - published: 59024
        target: 9001
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    configs:
      - source: localtime_shanghai
        target: /etc/localtime
    volumes:
      - minio_erasure_code_data_2:/minio_erasure_code_data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == GuangZhou-CentOS
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
    command: server http://minio{1...3}/minio_erasure_code_data --console-address ":9001"
    secrets:
      - source: minio_root_user
        mode: 0600
      - source: minio_root_password
        mode: 0600
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    hostname: minio3
    ports:
      - published: 59035
        target: 9000
        protocol: tcp
        mode: ingress
      - published: 59034
        target: 9001
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    configs:
      - source: localtime_shanghai
        target: /etc/localtime
    volumes:
      - minio_erasure_code_data_3:/minio_erasure_code_data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == GuangZhou-CentOS
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
    command: server http://minio{1...3}/minio_erasure_code_data --console-address ":9001"
    secrets:
      - source: minio_root_user
        mode: 0600
      - source: minio_root_password
        mode: 0600
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

configs:
  localtime_shanghai:
    name: localtime_shanghai
    external: true

secrets:
  minio_root_user:
    name: minio_root_user_v1
    external: false
    file: ./conf/secrets/minio_root_user.txt
  minio_root_password:
    name: minio_root_password_v1
    external: false
    file: ./conf/secrets/minio_root_password.txt

volumes:
  minio_filesystem_data:
    name: minio_filesystem_data
    driver: local
  minio_erasure_code_data_1:
    name: minio_erasure_code_data_1
    driver: local
  minio_erasure_code_data_2:
    name: minio_erasure_code_data_2
    driver: local
  minio_erasure_code_data_3:
    name: minio_erasure_code_data_3
    driver: local

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true