version: "3.9"

services:
  minio1:
    image: minio/minio:${IMAGE_VERSION:-latest}
    hostname: minio1
    volumes:
      - minio1-data:/export
    ports:
      - "9101:9000"
    networks:
      - cluster
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.hostname == Cloud
    command: server http://minio{1...4}/export
    secrets:
      - minio_access_key
      - minio_secret_key
    environment:
      MINIO_ACCESS_KEY: /run/secrets/minio_access_key
      MINIO_SECRET_KEY: /run/secrets/minio_secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:${IMAGE_VERSION:-latest}
    hostname: minio2
    volumes:
      - minio2-data:/export
    ports:
      - "9102:9000"
    networks:
      - cluster
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.hostname == Cloud
    command: server http://minio{1...4}/export
    secrets:
      - minio_access_key
      - minio_secret_key
    environment:
      MINIO_ACCESS_KEY: /run/secrets/minio_access_key
      MINIO_SECRET_KEY: /run/secrets/minio_secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:${IMAGE_VERSION:-latest}
    hostname: minio3
    volumes:
      - minio3-data:/export
    ports:
      - "9103:9000"
    networks:
      - cluster
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.hostname == VPS
    command: server http://minio{1...4}/export
    secrets:
      - minio_access_key
      - minio_secret_key
    environment:
      MINIO_ACCESS_KEY: /run/secrets/minio_access_key
      MINIO_SECRET_KEY: /run/secrets/minio_secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:${IMAGE_VERSION:-latest}
    hostname: minio4
    volumes:
      - minio4-data:/export
    ports:
      - "9104:9000"
    networks:
      - cluster
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == Bandwagon
    command: server http://minio{1...4}/export
    secrets:
      - minio_access_key
      - minio_secret_key
    environment:
      MINIO_ACCESS_KEY: /run/secrets/minio_access_key
      MINIO_SECRET_KEY: /run/secrets/minio_secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  cluster:
    name: cluster
    driver: overlay
    external: true

secrets:
  minio_secret_key:
    external: true
  minio_access_key:
    external: true

volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data: