version: "3.9"

services:
  minio-1:
    image: minio/minio:latest
    hostname: minio-1
    volumes:
      - minio:/data:rw
    ports:
      - 9003:9000
    networks:
      - minio
    command: server http://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - 'node.hostname == Cloud'
          - 'node.id == 0s4487ohhl7elxnugia34tbwl'

networks:
  minio:
    name: minio
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true

volumes:
  minio:
    name: minio
    driver: local