version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    hostname: minio
    ports:
      - "59005:9000"
    networks:
      - cluster
    volumes:
      - minio_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.hostname == ShangHai-CentOS
    command: server /data
    secrets:
      - minio_access_key
      - minio_secret_key
    environment:
      MINIO_ACCESS_KEY_FILE: /run/secrets/minio_access_key
      MINIO_SECRET_KEY_FILE: /run/secrets/minio_secret_key
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true

secrets:
  minio_access_key:
    name: minio_access_key
    external: false
    file: ./conf/secrets/minio_access_key.txt
  minio_secret_key:
    name: minio_secret_key
    external: false
    file: ./conf/secrets/minio_secret_key.txt

volumes:
  minio_data:
    name: minio_data
    external: false