version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.RELEASE.2022-10-24T18-35-07Z
    hostname: minio
    ports:
      - published: 59005
        target: 9000
        protocol: tcp
        mode: ingress
      - published: 59004
        target: 9001
        protocol: tcp
        mode: ingress
    networks:
      - cluster
    configs:
      - source: localtime_shanghai
        target: /etc/localtime
    volumes:
      - minio_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
    command: server /data
    secrets:
      - source: minio_access_key
        mode: 0600
      - source: minio_secret_key
        mode: 0600
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_access_key
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_secret_key
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

configs:
  localtime_shanghai:
    name: localtime_shanghai
    external: true

secrets:
  minio_access_key:
    name: minio_access_key_v1
    file: ./conf/secrets/minio_access_key.txt
  minio_secret_key:
    name: minio_secret_key_v1
    file: ./conf/secrets/minio_secret_key.txt

volumes:
  minio_data:
    name: minio_data
    external: false

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true