version: "3.9"

services:
  minio-server:
    image: minio/minio:${MINIO_VERSION:-RELEASE.2021-04-06T23-11-00Z}
    container_name: minio
    restart: "no"
    ports:
      - "59005:9000"
      - "59004:9001"
    volumes:
      - "/media/psf/Docker/Minio/conf/localtime:/etc/localtime"
      - "/media/psf/minio:/data:rw"
    networks:
      develop:
        ipv4_address: 172.19.0.34
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-MINIO_SECRET_KEY}
    command: server --console-address :9001 /data

  minio-client:
    container_name: mc
    image: minio/mc:${MC_VERSION:-RELEASE.2021-04-22T17-40-00Z}
    restart: "no"
    network_mode: host
    entrypoint: "tail -f /dev/null"
    volumes:
      - /media/psf/Docker/Minio/conf/localtime:/etc/localtime
      - /media/psf/Docker/Minio/conf/mc:/root/.mc:rw

networks:
  develop:
    external: true