version: "3.9"

services:
  minio1:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    hostname: minio1
    volumes:
      - minio1-data:/data
    ports:
      - "63814:9000"
    networks:
      - cluster
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.hostname == Cloud
    command: server http://minio{1...4}/data
    secrets:
      - access_key
      - secret_key
    environment:
      MINIO_ACCESS_KEY: /run/secrets/access_key
      MINIO_SECRET_KEY: /run/secrets/secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    hostname: minio2
    volumes:
      - minio2-data:/data
    ports:
      - "63815:9000"
    networks:
      - cluster
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.hostname == Cloud
    command: server http://minio{1...4}/data
    secrets:
      - access_key
      - secret_key
    environment:
      MINIO_ACCESS_KEY: /run/secrets/access_key
      MINIO_SECRET_KEY: /run/secrets/secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    hostname: minio3
    volumes:
      - minio3-data:/data
    ports:
      - "63816:9000"
    networks:
      - cluster
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.hostname == Cloud
    command: server http://minio{1...4}/data
    secrets:
      - access_key
      - secret_key
    environment:
      MINIO_ACCESS_KEY: /run/secrets/access_key
      MINIO_SECRET_KEY: /run/secrets/secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    hostname: minio4
    volumes:
      - minio4-data:/data
    ports:
      - "63817:9000"
    networks:
      - cluster
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.hostname == Cloud
    command: server http://minio{1...4}/data
    secrets:
      - access_key
      - secret_key
    environment:
      MINIO_ACCESS_KEY: /run/secrets/access_key
      MINIO_SECRET_KEY: /run/secrets/secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  cluster:
    name: cluster
    driver: overlay
    external: true

secrets:
  access_key:
    external: true
  secret_key:
    external: true

volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data: