version: "3.9"

services:
  dbgp-proxy:
    image: banjintaohua/dbgp-proxy:alpine
    ports:
      - published: 59002
        target: 9001
        protocol: tcp
        mode: ingress
      - published: 59003
        target: 9003
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.platform.os == linux
          - node.hostname != California-CentOS
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - cluster

networks:
  cluster:
    name: cluster
    driver: overlay
    external: true