version: "3.9"

services:
  camunda:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: camunda-bpm-platform:tomcat-7.10.0
    container_name: camunda
    ports:
      - "58088:8080"
    working_dir: /camunda
    volumes:
      - ./log/:/camunda/logs/:rw
      - ./conf/bpm-platform.xml:/camunda/conf/bpm-platform.xml:rw
      - ./conf/web.xml:/camunda/webapps/engine-rest/WEB-INF/web.xml:rw
    restart: "always"
    networks:
      develop:
        ipv4_address: 172.19.0.38
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME:-camunda}
      DB_PASSWORD: ${DB_PASSWORD:-camunda}
      DB_VALIDATE_ON_BORROW: "true"
      DB_VALIDATION_QUERY: "SELECT 1"
      WAIT_FOR: "mariadb:3306"
      TZ: "Asia/Shanghai"

networks:
  develop:
    external: true