version: "3.9"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "58086:8086"
    volumes:
      - /media/psf/Docker/InfluxDB/conf/influxdb.conf:/etc/influxdb/influxdb.conf
      - /media/psf/Docker/InfluxDB/data:/var/lib/influxdb
    restart: on-failure
    command: -config /etc/influxdb/influxdb.conf
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"
      INFLUXDB_DB: ${INFLUXDB_DB:-prometheus}
      INFLUXDB_ADMIN_ENABLED: ${INFLUXDB_ADMIN_ENABLED:-true}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-admin}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:-admin}
      INFLUXDB_USER: ${INFLUXDB_USER:-root}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD:-changeme}

networks:
  develop:
    external: true