version: "3.9"

services:
  php-56:
    image: php:5.6.40-fpm
    ports:
      - published: 59006
        target: 9000
        protocol: tcp
        mode: ingress
    configs:
      - source: php_56_xdebug_config
        target: /usr/local/etc/php/conf.d/dexbug.ini
    volumes:
      - nfs_data:/var/www/php:rw
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

  php-74:
    image: php:7.4.20-fpm
    ports:
      - published: 59007
        target: 9000
        protocol: tcp
        mode: ingress
    configs:
      - source: php_74_xdebug_config
        target: /usr/local/etc/php/conf.d/dexbug.ini
    volumes:
      - nfs_data:/var/www/php:rw
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

  php-80:
    image: php:8.0.2-fpm
    ports:
      - published: 59008
        target: 9000
        protocol: tcp
        mode: ingress
    volumes:
      - nfs_data:/var/www/php:rw
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux
    environment:
      TZ: "Asia/Shanghai"

configs:
  php_56_xdebug_config:
    name: php_56_xdebug_config
    file: ./conf/php-56/php.d/xdebug.ini
    external: false
  php_74_xdebug_config:
    name: php_74_xdebug_config
    file: ./conf/php-74/php.d/xdebug.ini
    external: false

volumes:
  nfs_data:
    name: nfs_data
    driver_opts:
      type: "nfs"
      o: "addr=nfs.banjintaohua.xyz,nolock,soft,rw"
      device: ":/nfs/share"
  php_56_data:
    name: php_56_data
    driver: local
  php_74_data:
    name: php_74_data
    driver: local
  php_80_data:
    name: php_80_data
    driver: local

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true