version: "3.5"

services:
  php-56:
    build: ./build
    container_name: php-56
    restart: always
    ports:
      - 9002:9000
    volumes:
      - ../../Php/Task:***REMOVED***:rw
      - ./logs/php-fpm:/var/log/php-fpm:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/xdebug.ini:/usr/local/etc/php/conf.d/dexbug.ini:ro

  php-74:
    image: php:7.4.8-fpm
    container_name: php-74
    restart: always
    ports:
      - 9004:9000

networks:
  default:
    external:
      name: develop

