version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: php-nginx
    restart: always
    ports:
      - 8088:80
    volumes:
      - ./log/nginx:/var/log/nginx:rw
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ../../Php/task:***REMOVED***:rw
    networks:
      - develop
    depends_on:
      - php-8
      - php-72
      - php-56

  php-56:
    build:
      context: ./build/php-56
      dockerfile: Dockerfile
    image: example/php-56:1.0
    container_name: php-56
    restart: always
    ports:
      - "9002:9000"
    volumes:
      - ./log/php-56/php-fpm:/var/log/php-fpm:rw
      - ./conf/php-56/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-56/xdebug.ini:/usr/local/etc/php/conf.d/dexbug.ini:ro
      - ./conf/php-56/php-fpm.d:/usr/local/etc/php-fpm.d:rw
      - ../../Php/task:***REMOVED***:rw
    networks:
      - develop

  php-72:
    build:
      context: ./build/php-72
      dockerfile: Dockerfile
    image: example/php-72:1.0
    container_name: php-72
    working_dir: /var/www/***REMOVED***
    user: root
    restart: always
    ports:
      - "9005:9000"
    volumes:
      - ./log/php-72/php-fpm:/var/log/php-fpm:rw
      - ./conf/php-72/php.ini:/usr/local/etc/php/php.ini:rw
      - ./conf/php-72/xdebug.ini:/usr/local/etc/php/conf.d/dexbug.ini:rw
      - ../../Php/epiboly/***REMOVED***:/var/www/***REMOVED***:rw
      - ../../Php/epiboly/***REMOVED***:/var/www/***REMOVED***:rw
    networks:
      - develop

  php-8:
    image: php:8.0.2-fpm
    container_name: php-8
    restart: always
    ports:
      - "9004:9000"
    networks:
      - develop

networks:
  develop:
    external: true