version: "3.9"

services:
  php-56:
    image: php:5.6.40-fpm
    ports:
      - "59006:9000"
    configs:
      - source: php_56_xdebug_config
        target: /usr/local/etc/php/conf.d/dexbug.ini
    volumes:
      - ./data/php-56:/var/www:rw
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux

  php-74:
    image: php:7.4.20-fpm
    ports:
      - "59007:9000"
    configs:
      - source: php_74_xdebug_config
        target: /usr/local/etc/php/conf.d/dexbug.ini
    volumes:
      - ./data/php-74:/var/www:rw
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux

  php-80:
    image: php:8.0.2-fpm
    ports:
      - "59008:9000"
    volumes:
      - ./data/php-80:/var/www:rw
    networks:
      - cluster
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 10s
        window: 60s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ShangHai-CentOS
          - node.platform.os == linux

configs:
  php_56_xdebug_config:
    name: php_56_xdebug_config
    file: ./conf/php-56/xdebug.ini
    external: false
  php_74_xdebug_config:
    name: php_74_xdebug_config
    file: ./conf/php-74/xdebug.ini
    external: false

networks:
  cluster:
    name: cluster
    driver: overlay
    attachable: true
    external: true

volumes:
  php_56_data:
    name: php_56_data
    driver: local
  php_74_data:
    name: php_74_data
    driver: local
  php_80_data:
    name: php_80_data
    driver: local