version: "3.9"

services:

  php-56:
    build:
      context: ./build/php-56
      dockerfile: Dockerfile
    image: banjintaohua/php-56:1.0
    container_name: php-56
    restart: always
    ports:
      - "59006:9000"
    volumes:
      - /home/docker/docker/PHP/log/php-56/php-fpm:/var/log/php-fpm:rw
      - /home/docker/docker/PHP/conf/php-56/php.ini:/usr/local/etc/php/php.ini:ro
      - /home/docker/docker/PHP/conf/php-56/xdebug.ini:/usr/local/etc/php/conf.d/dexbug.ini:ro
      - /home/docker/docker/PHP/conf/php-56/php-fpm.d:/usr/local/etc/php-fpm.d:rw
      - /home/docker/docker/PHP/conf/php-56/ssh:/root/.ssh:rw
      - /media/psf/Php:/var/www/php:rw
    working_dir: /var/www/php
    environment:
      TZ: "Asia/Shanghai"
      ALL_PROXY: ${ALL_PROXY:-}
    networks:
      develop:
        ipv4_address: 172.19.0.56

  php-74:
    build:
      context: ./build/php-74
      dockerfile: Dockerfile
    image: banjintaohua/php-74:1.1
    container_name: php-74
    extra_hosts:
      - ${EXTRA_HOSTS}
      - ${HOST_DOCKER_INTERNAL}
    user: root
    restart: always
    ports:
      - "59007:9000"
    volumes:
      - /home/docker/docker/PHP/log/php-74/php-fpm:/var/log/php-fpm:rw
      - /home/docker/docker/PHP/conf/php-74/php.ini:/usr/local/etc/php/php.ini:rw
      - /home/docker/docker/PHP/conf/php-74/xdebug.ini:/usr/local/etc/php/conf.d/dexbug.ini:rw
      - /home/docker/docker/PHP/conf/php-74/ssh:/root/.ssh:rw
      - /media/psf/Php:/var/www/php:rw
    working_dir: /var/www/php
    environment:
      TZ: "Asia/Shanghai"
    networks:
      develop:
        ipv4_address: 172.19.0.74

  php-81:
    build:
      context: ./build/php-81
      dockerfile: Dockerfile
    image: banjintaohua/php-81:1.1
    container_name: php-81
    restart: always
    ports:
      - "59008:9000"
    volumes:
      - /home/docker/docker/PHP/log/php-81/php-fpm:/var/log/php-fpm:rw
      - /home/docker/docker/PHP/conf/php-81/php.ini:/usr/local/etc/php/php.ini:rw
      - /home/docker/docker/PHP/conf/php-81/xdebug.ini:/usr/local/etc/php/conf.d/dexbug.ini:rw
      - /home/docker/docker/PHP/conf/php-81/ssh:/root/.ssh:rw
      - /media/psf/Php:/var/www/php:rw
    working_dir: /var/www/php
    environment:
      TZ: "Asia/Shanghai"
    networks:
      develop:
        ipv4_address: 172.19.0.81

networks:
  develop:
    external: true
