version: "3.9"

services:
  php-fpm:
    image: php:5.6.40-fpm
    ports:
      - "59006:9000"
    volumes:
      - php-56:/var/www:rw
    networks:
      - php-56
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 10s
        window: 60s

networks:
  php-56:
    name: php-56
    driver: overlay

volumes:
  php-56:
    name: php-56
    driver: local