version: "3.9"

services:

  php-56:
    build:
      context: ./build/php-56
      dockerfile: Dockerfile
    image: banjintaohua/php-56:1.0
    container_name: php-56
    restart: always
    ports:
      - "59006:9000"
    volumes:
      - ./log/php-56/php-fpm:/var/log/php-fpm:rw
      - ./conf/php-56/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-56/xdebug.ini:/usr/local/etc/php/conf.d/dexbug.ini:ro
      - ./conf/php-56/php-fpm.d:/usr/local/etc/php-fpm.d:rw
      - /media/psf/Php:/var/www/php:rw
    working_dir: /var/www/php
    environment:
      TZ: "Asia/Shanghai"
      ALL_PROXY: ${ALL_PROXY:-}
    networks:
      - develop

  php-74:
    build:
      context: ./build/php-74
      dockerfile: Dockerfile
    image: banjintaohua/php-74:1.1
    container_name: php-74
    extra_hosts:
      - ${EXTRA_HOSTS}
      - ${HOST_DOCKER_INTERNAL}
    user: root
    restart: always
    ports:
      - "59007:9000"
    volumes:
      - ./log/php-74/php-fpm:/var/log/php-fpm:rw
      - ./conf/php-74/php.ini:/usr/local/etc/php/php.ini:rw
      - ./conf/php-74/xdebug.ini:/usr/local/etc/php/conf.d/dexbug.ini:rw
      - /media/psf/Php:/var/www/php:rw
    working_dir: /var/www/php
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - develop

  php-8:
    image: php:8.0.2-fpm
    container_name: php-8
    restart: always
    ports:
      - "59008:9000"
    working_dir: /var/www/php
    networks:
      - develop
    environment:
      TZ: "Asia/Shanghai"

networks:
  develop:
    external: true
