version: "3.9"

services:
  redis:
    image: redis:${REDIS_VERSION:-6.0.9}
    container_name: redis
    restart: "always"
    ports:
      - "56379:6379"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    networks:
      - develop
    command: "redis-server /usr/local/etc/redis/redis.conf"
    environment:
      TZ: "Asia/Shanghai"

networks:
  develop:
    external: true
