version: "3.7"

services:
    redis:
      image: redis:latest
      container_name: redis
      restart: always
      extra_hosts:
        - "host.docker.internal:host-gateway"
      ports:
        - "6379:6379"
      volumes:
        - ./conf/redis.conf:/etc/redis/redis.conf
        - ./data:/data
      networks:
        - develop
      command: redis-server /etc/redis/redis.conf

networks:
  develop:
    external: true