version: '3.5'

services:
    redis:
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - redis:/etc/redis/redis.conf
        - redis:/data
      networks:
        - redis
      deploy:
        replicas: 3
        update_config:
          parallelism: 2
          failure_action: rollback
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 2

networks:
  redis:
    name: redis
    driver: overlay

volumes:
  redis:
    driver: local
    name: redis