version: "3.9"

services:
    redis:
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - redis:/etc/redis/redis.conf
        - redis:/data
      networks:
        - redis
      deploy:
        replicas: 3
        restart_policy:
          condition: any
          delay: 10s
          window: 60s

networks:
  redis:
    name: redis
    driver: overlay

volumes:
  redis:
    driver: local
    name: redis