version: "3.9"

services:
    redis:
      image: redis:latest
      ports:
        - "56379:6379"
      volumes:
        - redis_data:/data
      networks:
        - redis
      deploy:
        replicas: 3
        restart_policy:
          condition: any
          delay: 10s
          window: 60s

networks:
  redis:
    name: redis
    driver: overlay

volumes:
  redis_data:
    name: redis_data
    driver: local
    external: false
