version: '3.5'

services:
  php-72:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: example/php-72:1.0
    container_name: php-72
    working_dir: /var/www/***REMOVED***
    user: root
    restart: always
    ports:
      - 9005:9000
    volumes:
      - ./conf/php.ini:/usr/local/etc/php/php.ini:rw
      - ./conf/xdebug.ini:/usr/local/etc/php/conf.d/dexbug.ini:rw
      - ../../Php/epiboly/***REMOVED***:/var/www/***REMOVED***:rw
      - ../../Php/epiboly/***REMOVED***:/var/www/***REMOVED***:rw
    networks:
      - develop

networks:
  develop:
    external: true

